---
sidebar: sidebar 
permalink: concept_lic_cp_restrictions.html 
keywords: license, licensing, Capacity Pools, restrictions 
summary: 容量プール ライセンス モデルを使用する際に適用される制限を以下に示します。 
---
= ONTAP Select容量プールライセンスの導入制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量プール ライセンス モデルを使用する際に適用される制限を以下に示します。

.クラスターごとに一貫したライセンス モデル
単一のONTAP Selectクラスタ内のすべてのノードは、同じライセンスモデル（容量階層または容量プールのいずれか）を使用する必要があります。単一クラスタ内のノードに異なるライセンスタイプを混在させることはできません。

.クラスタ内のすべてのノードは同じライセンスマネージャインスタンスを使用します
ONTAP Selectクラスタ内のCapacity Poolライセンスを持つすべてのノードは、同じLicense Managerインスタンスを使用する必要があります。各DeployインスタンスにはLicense Managerインスタンスが1つずつ存在するため、この制限は、クラスタ内のすべてのノードを同じDeployインスタンスで管理する必要があるという既存の要件を言い換えたものです。

.ノードごとに1つの容量プール
各ノードは、1つの容量プールからのみストレージをリースできます。1つのノードで2つ以上のプールを使用することはできません。

.HAペアのノードに同じプール
単一のHAペア内の両ノードは、同じ容量プールからストレージをリースする必要があります。ただし、同一クラスター内の異なるHAペアは、同じライセンスマネージャーによって管理される異なるプールからストレージをリースできます。

.ストレージライセンスの期間
NetAppからストレージライセンスを取得する際には、ライセンス期間を選択する必要があります。例えば、ライセンスの有効期間は1年間とすることができます。

.データ集約リース期間
ONTAP Selectノードがデータアグリゲートのストレージリースを要求すると、License Managerは容量プールの設定に基づいて特定の期間のリースを提供します。各プールのリース期間は1時間から7日間まで設定できます。デフォルトのリース期間は24時間です。

.デプロイに割り当てられた静的IPアドレス
容量プール ライセンスを使用する場合は、デプロイ管理ユーティリティに静的 IP アドレスを割り当てる必要があります。
