---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: 容量プールのライセンスモデルは、容量階層モデルとは異なります。個々のノードに専用のストレージ容量を割り当てるのではなく、ストレージ容量はプールに割り当てられ、複数のノード間で共有されます。容量プールモデルをサポートするために、追加のコンポーネントとプロセスが作成されています。 
---
= ONTAP Select容量プール ライセンス モデルの操作の詳細
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量プールのライセンスモデルは、容量階層モデルとは異なります。個々のノードに専用のストレージ容量を割り当てるのではなく、ストレージ容量はプールに割り当てられ、複数のノード間で共有されます。容量プールモデルをサポートするために、追加のコンポーネントとプロセスが作成されています。



== ライセンスマネージャー

ライセンスマネージャは、Deploy管理ユーティリティの各インスタンス内で個別のプロセスとして実行されます。LMが提供する機能には、以下のものがあります。

* 容量プールライセンスのシリアル番号に基づいて、各ノードに固有の20桁のシリアル番号を生成します。
* ONTAP Selectノードからの要求に基づいて、共有容量プールから容量のリースを作成します。
* デプロイユーザーインターフェースを通じてプールの使用状況情報をレポートする




== リースの特徴

容量プールライセンスを使用するノードで各データアグリゲートに割り当てられるストレージには、関連付けられたリースが必要です。ノードはストレージリースを要求し、利用可能な容量がある場合、ライセンスマネージャーはリースで応答します。各リースには、以下の明示的または暗黙的な属性があります。

* ライセンスマネージャ すべてのONTAP Selectノードは 1 つのライセンスマネージャインスタンスに関連付けられます
* 容量プール すべてのONTAP Selectノードは1つの容量プールに関連付けられています
* ストレージ割り当て リースで特定の容量値が割り当てられます
* 有効期限とリースの期間は、ユーザー設定に応じて 1 時間から 7 日間です。




== ライセンスロックID

License Managerの各インスタンス、そして対応するDeployユーティリティの各インスタンスは、一意の128ビット番号で識別されます。この番号は、9桁のCapacity Poolライセンスのシリアル番号と組み合わされ、プールを特定のLicense Managerインスタンス（実質的にはDeployインスタンス）にロックします。NetAppNetAppファイル（NLF）を生成する際に、 NetAppサポートサイトで両方の値を提供する必要があります。

次の方法で、Web ユーザー インターフェイスを使用して、Deploy インスタンスのライセンス ロック ID を確認できます。

* 「はじめに」ページ このページは、Deployに初めてサインインすると表示されます。ページ右上のドロップダウンボックスをクリックし、「はじめに」を選択してもこのページを表示できます。LLIDは「ライセンスの追加」セクションに表示されます。
* 管理 ページ上部の *管理* タブをクリックし、*システム* と *設定* をクリックします。




== 基本的なリース操作

ONTAP Selectノードは、データアグリゲートが作成、拡張、または変更されるたびに、有効な容量リースを検索または要求する必要があります。以前の要求で取得され、まだ有効なリースを使用することも、必要に応じて新しいリースを要求することもできます。ONTAPONTAP Selectノードは、容量プールのリースを検索するために、以下の手順を実行します。

. 既存のリースがノードにある場合、次の条件がすべて満たされている限り、そのリースが使用されます。
+
** リースは期限切れではありません
** 集約のストレージ要求がリース容量を超えない


. 既存のリースが見つからない場合、ノードはライセンス マネージャーに新しいリースを要求します。




== ストレージ容量を容量プールに戻す

ストレージ容量は必要に応じて容量プールから割り当てられ、新しいリクエストごとにプール内の利用可能なストレージ容量が減少する可能性があります。ストレージ容量は、以下のような状況でプールに返却されます。

* データ集約のリースが期限切れになり、ノードによって更新されない
* データ集計が削除されました



NOTE: ONTAP Select仮想マシンが削除された場合、アクティブなリースは期限切れになるまで有効のままです。期限切れになると、容量はプールに戻されます。
