---
sidebar: sidebar 
permalink: concept_api_understanding_scripts.html 
keywords: rest api, deploy rest api, rest, python, python scripts, understanding 
summary: サンプルのPythonスクリプトを使用すると、様々なタスクを実行できます。実際のDeployインスタンスで使用する前に、スクリプトの内容を理解しておく必要があります。 
---
= ONTAP Select Deploy の Python スクリプトを理解する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サンプルのPythonスクリプトを使用すると、様々なタスクを実行できます。実際のDeployインスタンスで使用する前に、スクリプトの内容を理解しておく必要があります。



== 共通の設計特性

スクリプトは、次の共通の特性を考慮して設計されています。

* クライアントマシンのコマンドラインインターフェースから実行 Pythonスクリプトは、適切に設定された任意のクライアントマシンから実行できます。詳細については、「始める前に」をご覧ください。
* CLI 入力パラメータを受け入れます。各スクリプトは、入力パラメータを通じて CLI で制御されます。
* 入力ファイルの読み取り 各スクリプトは、その目的に基づいて入力ファイルを読み取ります。クラスターを作成または削除する場合は、JSON 構成ファイルを提供する必要があります。ノードライセンスを追加する場合は、有効なライセンスファイルを提供する必要があります。
* 共通サポートモジュールを使用する 共通サポートモジュール _deploy_requests.py_ には、1つのクラスが含まれています。このクラスは各スクリプトによってインポートされ、使用されます。




== クラスタを作成します。

ONTAP Selectクラスタは、cluster.pyスクリプトを使用して作成できます。CLIパラメータとJSON入力ファイルの内容に基づいて、以下のようにスクリプトを環境に合わせて変更できます。

* ハイパーバイザーは、Deploy のリリースに応じて ESXi または KVM にデプロイできます。ESXiにデプロイする場合、ハイパーバイザーは vCenter によって管理することも、スタンドアロンホストとして使用することもできます。
* クラスター サイズ 単一ノードまたは複数ノードのクラスターを展開できます。
* 評価ライセンスまたは本番環境ライセンス 評価ライセンスまたは本番環境用に購入したライセンスを使用してクラスターをデプロイできます。


スクリプトの CLI 入力パラメータは次のとおりです。

* デプロイサーバーのホスト名またはIPアドレス
* 管理者ユーザーアカウントのパスワード
* JSON構成ファイルの名前
* メッセージ出力の詳細フラグ




== ノードライセンスを追加する

本番環境のクラスターをデプロイする場合は、スクリプト_add_license.py_を使用して各ノードにライセンスを追加する必要があります。ライセンスはクラスターのデプロイ前でもデプロイ後でも追加できます。

スクリプトの CLI 入力パラメータは次のとおりです。

* デプロイサーバーのホスト名またはIPアドレス
* 管理者ユーザーアカウントのパスワード
* ライセンスファイルの名前
* ライセンスを追加する権限を持つONTAPユーザー名
* ONTAPユーザーのパスワード




== クラスターを削除する

スクリプト _delete_cluster.py_ を使用して、既存のONTAP Selectクラスタを削除できます。

スクリプトの CLI 入力パラメータは次のとおりです。

* デプロイサーバーのホスト名またはIPアドレス
* 管理者ユーザーアカウントのパスワード
* JSON構成ファイルの名前

