---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: Representational State Transfer（REST）は、分散Webアプリケーションの作成に使用される形式です。WebサービスAPIの設計においては、これによってサーバベースのリソースの公開とその状態の管理に関する一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準を使用して、 ONTAP Selectクラスタを導入および管理するための柔軟な基盤を提供します。 
---
= ONTAP Selectクラスタの導入と管理のための REST Web サービス基盤
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Representational State Transfer（REST）は、分散Webアプリケーションの作成に使用される形式です。WebサービスAPIの設計においては、これによってサーバベースのリソースの公開とその状態の管理に関する一連のテクノロジとベストプラクティスが確立されます。主流のプロトコルと標準を使用して、 ONTAP Selectクラスタを導入および管理するための柔軟な基盤を提供します。



== 建築と古典的な制約

RESTはロイ・フィールディング博士によって正式に発表された。 https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["論文"] 2000年にカリフォルニア大学アーバイン校で。発表されました。一連の制約を通してアーキテクチャスタイルを定義し、Webベースのアプリケーションとその基盤となるプロトコルを総合的に改善します。これらの制約により、ステートレスな通信プロトコルを用いたクライアント/サーバーアーキテクチャに基づくRESTful Webサービスアプリケーションが構築されます。



== リソースと状態の表示

リソースはWebベース システムの基本コンポーネントです。REST Webサービス アプリケーションを作成する場合、設計の早い段階で次の作業を行います。

* システムまたはサーバーベースのリソースの識別 すべてのシステムはリソースを使用し、維持します。リソースには、ファイル、ビジネス トランザクション、プロセス、管理エンティティなどがあります。REST Webサービスに基づいてアプリケーションを設計する際に行う最初の作業の1つは、リソースを識別することです。
* リソースの状態と関連する状態操作の定義 リソースは常に有限の数の状態のいずれかになります。状態は明確に定義する必要があり、状態の変化に作用する操作も明確に定義する必要があります。


一般的な CRUD (作成、読み取り、更新、削除) モデルに従ってリソースの状態にアクセスし、変更するために、クライアントとサーバーの間でメッセージが交換されます。



== URIエンドポイント

すべてのRESTリソースは、明確に定義されたアドレス指定方式を使用して定義、提供される必要があります。リソースが置かれているエンドポイントは、Uniform Resource Identifier（URI）で識別されます。URIは、ネットワークの各リソースに一意の名前を作成するための一般的なフレームワークです。Uniform Resource Locator（URL）は、リソースを識別してアクセスするためにWebサービスで使用されるURIの一種です。リソースは、通常、ファイル ディレクトリに似た階層構造で公開されます。



== HTTPメッセージ

Hypertext Transfer Protocol（HTTP）は、Webサービスのクライアントとサーバがリソースに関する要求と応答のメッセージを交換する際に使用するプロトコルです。Web サービス アプリケーションの設計の一環として、HTTP 動詞 (GET や POST など) がリソースおよび対応する状態管理アクションにマッピングされます。

HTTPはステートレスです。したがって、関連する要求と応答のセットを 1 つのトランザクションに関連付けるには、要求/応答データ フローで伝送される HTTP ヘッダーに追加情報を含める必要があります。



== JSONの形式

情報はさまざまな方法で構造化してクライアントとサーバー間で転送できますが、最も一般的なオプション (Deploy REST API で使用されるオプション) は JavaScript Object Notation (JSON) です。JSONは、単純なデータ構造をプレーン テキストで表現するための業界標準であり、リソースについての状態情報の転送に使用されます。
