---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 内部および外部のONTAP Selectネットワークの特性。 
---
= ONTAP Selectの内部および外部ネットワーク
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の内部ネットワークと外部ネットワークの特性。



== ONTAP Select内部ネットワーク

ONTAP Selectの内部ネットワークは、製品のマルチノード版にのみ存在し、 ONTAP Selectクラスタにクラスタ通信、HAインターコネクト、および同期レプリケーションサービスを提供します。このネットワークには、以下のポートとインターフェースが含まれます。

* *e0c、e0d。*クラスタ ネットワーク LIF のホスティング
* *e0e.*RSM LIF のホスティング
* *e0f.*HAインターコネクトLIFのホスティング


このネットワークのスループットとレイテンシは、 ONTAP Selectクラスタのパフォーマンスと耐障害性を決定づける上で非常に重要です。クラスタのセキュリティを確保し、システムインターフェースを他のネットワークトラフィックから分離するためには、ネットワークの分離が不可欠です。そのため、このネットワークはONTAP Selectクラスタ専用にする必要があります。


NOTE: Selectクラスタトラフィック以外のトラフィック（アプリケーショントラフィックや管理トラフィックなど）にSelect内部ネットワークを使用することはサポートされていません。ONTAP内部VLANには、他のVMやホストを配置することはできません。

内部ネットワークを通過するネットワークパケットは、専用のVLANタグ付きレイヤー2ネットワーク上を通過する必要があります。これは、以下のいずれかのタスクを実行することで実現できます。

* 内部仮想NIC（e0c～e0f）にVLANタグ付きポートグループを割り当てる（VSTモード）
* ネイティブVLANが他のトラフィックに使用されていない上流スイッチによって提供されるネイティブVLANを使用する（VLAN IDのないポートグループを割り当てる、つまりESTモード）


いずれの場合も、内部ネットワーク トラフィックの VLAN タグ付けはONTAP Select VM の外部で実行されます。


NOTE: ESXの標準vSwitchと分散vSwitchのみがサポートされます。その他の仮想スイッチやESXホスト間の直接接続はサポートされません。内部ネットワークは完全にオープンである必要があります。NATやファイアウォールはサポートされません。

ONTAP Selectクラスタ内では、ポートグループと呼ばれる仮想レイヤ2ネットワークオブジェクトを使用して、内部トラフィックと外部トラフィックが分離されます。これらのポートグループをvSwitchに適切に割り当てることは、特にクラスタ、HAインターコネクト、ミラーレプリケーションサービスを提供する内部ネットワークでは非常に重要です。これらのネットワークポートへのネットワーク帯域幅が不十分だと、パフォーマンスが低下し、クラスタノードの安定性にも影響する可能性があります。そのため、4ノード、6ノード、および8ノードのクラスタでは、内部ONTAP Selectネットワークで10Gb接続を使用する必要があります。1Gb NICはサポートされていません。ただし、 ONTAP Selectクラスタへの受信データフローを制限しても、クラスタの信頼性の高い動作には影響しないため、外部ネットワークとのトレードオフが可能です。

2ノードクラスタでは、内部トラフィック用に4つの1Gbポートを使用するか、4ノードクラスタに必要な2つの10Gbポートの代わりに1つの10Gbポートを使用できます。サーバの環境条件により4枚の10Gb NICカードを搭載できない場合は、2枚の10Gb NICカードを内部ネットワークに使用し、2枚の1Gb NICカードを外部ONTAPネットワークに使用できます。



=== 内部ネットワークの検証とトラブルシューティング

マルチノードクラスタの内部ネットワークは、ネットワーク接続チェッカー機能を使用して検証できます。この関数は、Deploy CLIから呼び出すことができます。 `network connectivity-check start`指示。

テストの出力を表示するには、次のコマンドを実行します。

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
このツールは、マルチノードSelectクラスタ内の内部ネットワークのトラブルシューティングにのみ役立ちます。シングルノードクラスタ（vNAS構成を含む）、 ONTAP DeployとONTAP Selectの接続、またはクライアント側の接続に関する問題のトラブルシューティングには使用しないでください。

クラスタ作成ウィザード（ ONTAP Deploy UIの一部）には、マルチノードクラスタの作成時に利用可能なオプションのステップとして、内部ネットワークチェッカーが含まれています。マルチノードクラスタにおいて内部ネットワークが果たす重要な役割を考慮すると、このステップをクラスタ作成ワークフローの一部にすることで、クラスタ作成操作の成功率が向上します。

ONTAP Deploy 2.10以降では、内部ネットワークで使用されるMTUサイズを7,500～9,000の間で設定できます。ネットワーク接続チェッカーを使用して、7,500～9,000のMTUサイズをテストすることもできます。デフォルトのMTU値は、仮想ネットワークスイッチの値に設定されています。環境内にVXLANなどのネットワークオーバーレイが存在する場合は、このデフォルト値をより小さい値に変更する必要があります。



== ONTAP Select外部ネットワーク

ONTAP Selectの外部ネットワークは、クラスタからのすべての送信通信を担うため、シングルノード構成とマルチノード構成の両方に存在します。このネットワークは内部ネットワークほど厳密に定義されたスループット要件を満たしていませんが、管理者はクライアントとONTAP VMの間にネットワークのボトルネックが生じないように注意する必要があります。パフォーマンスの問題がONTAP Selectの問題と誤認される可能性があるためです。


NOTE: 内部トラフィックと同様に、外部トラフィックはvSwitchレイヤ（VST）と外部スイッチレイヤ（EST）でタグ付けできます。さらに、外部トラフィックはONTAP Select VM自体によってVGTと呼ばれるプロセスでタグ付けされます。セクションを参照link:concept_nw_data_mgmt_separation.html["データと管理トラフィックの分離"]詳細についてはこちらをご覧ください。

次の表は、ONTAP Select の内部ネットワークと外部ネットワークの主な違いを示しています。

*内部ネットワークと外部ネットワークのクイックリファレンス*

[cols="3*"]
|===
| 説明 | 内部ネットワーク | 外部ネットワーク 


| ネットワークサービス | クラスター HA/IC RAID SyncMirror (RSM) | データ管理インタークラスタ（SnapMirrorおよびSnapVault） 


| ネットワーク分離 | 必須 | オプション 


| フレームサイズ（MTU） | 7,500～9,000 | 1,500（デフォルト）9,000（サポート） 


| IPアドレスの割り当て | 自動生成 | ユーザ定義 


| DHCPのサポート | いいえ | いいえ 
|===


=== NICチーミング

内部ネットワークと外部ネットワークが、高いパフォーマンスとフォールトトレランスを実現するために必要な帯域幅と回復力の両方を備えていることを確認するために、物理ネットワークアダプターのチーミングが推奨されます。10Gbリンクを1つ備えた2ノードクラスター構成がサポートされています。ただし、NetAppでは、ONTAP Selectクラスタの内部ネットワークと外部ネットワークの両方でNICチーミングを使用することをベストプラクティスとして推奨します。



=== MACアドレス生成

すべてのONTAP Selectネットワークポートに割り当てられるMACアドレスは、付属の導入ユーティリティによって自動的に生成されます。このユーティリティは、NetApp固有のプラットフォーム専用OUI（Organizationally Unique Identifier）を使用して、FASシステムとの競合がないことを確認します。このアドレスのコピーは、 ONTAP SelectインストールVM（ONTAP Deploy）内の内部データベースに保存され、将来のノード導入時に誤って再割り当てされることを防ぎます。管理者は、ネットワークポートに割り当てられたMACアドレスをいかなる時点でも変更しないでください。
