---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: ONTAP Selectは、 FASおよびAFFアレイに搭載されているストレージ効率オプションと同様のストレージ効率オプションを提供します。 
---
= ONTAP Selectストレージ効率サポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectは、 FASおよびAFFアレイに搭載されているストレージ効率オプションと同様のストレージ効率オプションを提供します。

オールフラッシュ VSAN または汎用フラッシュ アレイを使用したONTAP Select仮想 NAS (vNAS) の展開では、SSD 以外の直接接続ストレージ (DAS) を使用したONTAP Selectのベスト プラクティスに従う必要があります。

SSD ドライブとプレミアム ライセンスを備えた DAS ストレージがある限り、新規インストールではAFFのようなパーソナリティが自動的に有効になります。

AFFのようなパーソナリティにより、インストール中に次のインライン SE 機能が自動的に有効になります。

* インラインゼロパターン検出
* ボリュームインライン重複排除
* ボリュームバックグラウンド重複排除
* 適応型インライン圧縮
* インライン データ コンパクション
* アグリゲート インライン重複排除
* 集約的なバックグラウンド重複排除


ONTAP Select ですべてのデフォルトのストレージ効率ポリシーが有効になっていることを確認するには、新しく作成されたボリュームで次のコマンドを実行します。

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: ONTAP Select 9.6以降からのアップグレードでは、プレミアムライセンスを使用してDAS SSDストレージにONTAP Selectをインストールする必要があります。さらに、 ONTAP Deployを使用したクラスタの初期インストール時に、「ストレージ効率の有効化」チェックボックスをオンにする必要があります。事前の条件が満たされていない場合、 ONTAPアップグレード後にAFFのようなパーソナリティを有効にするには、ブート引数を手動で作成し、ノードを再起動する必要があります。詳細については、テクニカルサポートにお問い合わせください。

.ONTAP Selectストレージ効率構成
次の表は、メディア タイプとソフトウェア ライセンスに応じて、デフォルトで有効になっている、またはデフォルトでは有効になっていないが推奨される、使用可能なさまざまなストレージ効率オプションをまとめたものです。

[cols="4"]
|===
| ONTAP Selectの機能 | DAS SSD (プレミアムまたはプレミアム XL^1^) | DAS HDD（全ライセンス） | vNAS（すべてのライセンス） 


| インラインゼロ検出 | はい（デフォルト） | はい ボリュームごとにユーザーが有効化 | はい ボリュームごとにユーザーが有効化 


| ボリュームインライン重複排除 | はい（デフォルト） | 使用不可 | サポート対象外 


| 32Kインライン圧縮（二次圧縮） | はい、ボリュームごとにユーザーが有効化します。 | はい ボリュームごとにユーザーが有効化 | サポート対象外 


| 8Kインライン圧縮（アダプティブ圧縮） | はい（デフォルト） | はい、ボリュームごとにユーザーが有効化できます | サポート対象外 


| バックグラウンド圧縮 | サポート対象外 | はい、ボリュームごとにユーザーが有効化できます | はい ボリュームごとにユーザーが有効化 


| 圧縮スキャナ | はい | はい | はい ボリュームごとにユーザーが有効化 


| インライン データ コンパクション | はい（デフォルト） | はい、ボリュームごとにユーザーが有効化できます | サポート対象外 


| 圧縮スキャナー | はい | はい | サポート対象外 


| アグリゲート インライン重複排除 | はい（デフォルト） | 該当なし | サポート対象外 


| ボリュームバックグラウンド重複排除 | はい（デフォルト） | はい、ボリュームごとにユーザーが有効化できます | はい ボリュームごとにユーザーが有効化 


| 集約的なバックグラウンド重複排除 | はい（デフォルト） | 該当なし | サポート対象外 
|===
[small]#^1^ ONTAP Select 9.6は、新しいライセンス（プレミアムXL）と新しいVMサイズ（ラージ）をサポートします。ただし、ラージVMはソフトウェアRAIDを使用したDAS構成でのみサポートされます。9.6リリースのラージONTAP Select VMでは、ハードウェアRAIDおよびvNAS構成はサポートされません。#

.DAS SSD構成のアップグレード動作に関する注意事項
ONTAP Select 9.6以降にアップグレードした後、 `system node upgrade-revert show`既存のボリュームのストレージ効率値を確認する前に、アップグレードが完了したことを示すコマンド。

ONTAP Select 9.6以降にアップグレードしたシステムでは、既存のアグリゲートまたは新規に作成されたアグリゲート上に作成された新しいボリュームは、新規導入で作成されたボリュームと同じ動作になります。ONTAPONTAP Selectコードアップグレード後の既存のボリュームのストレージ効率ポリシーは、新規に作成されたボリュームとほぼ同じですが、若干の違いがあります。

シナリオ1:: アップグレード前にボリューム上でストレージ効率ポリシーが有効になっていなかった場合は、次のようになります。
+
--
* ボリューム `space guarantee = volume`インライン データ圧縮、アグリゲート インライン重複排除、およびアグリゲート バックグラウンド重複排除が有効になっていません。これらのオプションはアップグレード後に有効にできます。
* ボリューム `space guarantee = none`バックグラウンド圧縮が有効になっていません。このオプションはアップグレード後に有効にできます。
* アップグレード後、既存のボリュームのストレージ効率ポリシーは自動に設定されます。


--
シナリオ2:: アップグレード前にボリューム上で一部のストレージ効率がすでに有効になっている場合は、次のようになります。
+
--
* ボリューム `space guarantee = volume`アップグレード後も違いは見られません。
* ボリューム `space guarantee = none`集計バックグラウンド重複排除がオンになっています。
* ボリューム `storage policy inline-only`ポリシーを自動に設定します。
* ユーザー定義のストレージ効率ポリシーを持つボリュームは、以下のボリュームを除いてポリシーに変更はありません。 `space guarantee = none` 。これらのボリュームでは、集約バックグラウンド重複排除が有効になっています。


--

