---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: ONTAP Selectの容量階層ライセンスまたは容量プールライセンスは、3つのプラットフォーム容量レベルのいずれかで購入できます。これらのライセンスによって、 ONTAP Selectを導入するホストの機能が決まります。 
---
= ONTAP Selectのプラットフォームライセンスについて学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectの容量階層または容量プールのライセンスは、標準、プレミアム、またはプレミアムXLレベルで購入できます。これらのライセンスによって、 ONTAP Selectを導入するホストの機能が決まります。



== プラットフォームライセンスが提供するもの

特定のライセンス オファリングによって、次の 2 つの領域におけるハイパーバイザー ホストの機能が決まります。

* インスタンスタイプ（CPU、メモリ）
* その他の機能


ライセンスは、StandardからPremium XLまで、機能の昇順で提供されています。通常、選択したライセンスオプションにより、そのレベルとそれより下位のすべてのレベルの機能が提供されます。例えば、Premiumレベルは、PremiumとStandardの両方の機能を利用できます。

次の表は、標準、プレミアム、プレミアム XL ライセンス オファリングの機能を比較したものです。

[cols="25,25,25,25,25"]
|===
2+| ライセンスはサポートされています... | Standard | Premium | プレミアムXL 


2+| インスタンスタイプ | 小型のみ | 小または中 | 小、中、大 


.2+| ハードディスクドライブ (HDD) は ... | ハードウェアRAID構成 | はい | はい | はい 


| vNAS構成 | はい | はい | はい 


.3+| ソリッド ステート ドライブ (SSD) は ... | ハードウェアRAID構成 | いいえ | はい | はい 


| ソフトウェアRAID構成 | いいえ | はい | はい 


| vNAS構成 | はい | はい | はい 


.3+| NVMe ドライブは ... | ハードウェアRAID構成 | いいえ | いいえ | はい 


| ソフトウェアRAID構成 | いいえ | いいえ | はい 


| vNAS構成 | はい | はい | はい 


2+| MetroCluster SDS | いいえ | はい | はい 
|===

NOTE: カーネルベースの仮想マシン (KVM) は、大規模なインスタンス タイプをサポートしていません。



== プラットフォームライセンスオファリングのハードウェアサポートを比較する

標準、プレミアム、プレミアムXLライセンスは、幅広いハードウェアとソフトウェアをサポートしています。ハードウェアとソフトウェアのバージョンに関する最新情報については、link:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^] 。

[role="tabbed-block"]
====
.コアアイテム
--
[cols="5"30"]
|===


2+| コアアイテムタイプ 3+| 説明 


2+| ホストプロトコル 3+| NFS、SMB/CIFS、iSCSI、NVMe over TCP 


2+| 展開オプション 3+| 単一ノード 2ノードクラスタ（HAペア） 4、6、または8ノードクラスタ 


2+| サポートされる容量（ノードあたり） 3+| 最大 400 TB の生データ (ESXi および KVM) 
|===
--
.ハードウェア
--
[cols="5"30"]
|===


2+| ハードウェアタイプ 3+| 説明 


2+| インスタンスサイズ | 小規模 | 中 | 大規模 


2+| CPUファミリー | Intel Xeon E5-26xx v3 (Haswell) 以降 | Intel Xeon E5-26xx v3 (Haswell) 以降 | Intel Xeon E5-26xx v3 (Haswell) 以降 


2+| ONTAP Select CPU / メモリ | 4 つの仮想 CPU (vCPU) / 16 GB の RAM | 8 個の vCPU / 64 GB の RAM | 16 個の vCPU / 128 GB の RAM 


2+| ホストCPU / メモリの最小要件 ^1^ | 6コア / 24GBのRAM | 10コア / 72GBのRAM | 18コア / 136GBのRAM 


2+| ネットワーク（ノードあたり） 3+| 単一ノードクラスタの場合は最低2つの1GbEポート、2ノードクラスタ（HAペア）の場合は最低4つの1GbEポート、4、6、または8ノードクラスタの場合は最低2つの10GbEポート 
|===
^1^ ハイパーバイザーに 2 つのコアと 8 GB の RAM を想定しています。

--
.ストレージ タイプ
--
次の表は、指定されたストレージに必要な最小限のライセンス タイプを示しています。 

[cols="5"30"]
|===


2+| ストレージ タイプ 3+| 説明 


2+| ライセンス タイプ | Standard | Premium | プレミアムXL 


2+| インスタンスサイズ | 小規模 | 小型・中型 | 小、中、大 


2+| ハードウェア RAID コントローラを備えたローカル DAS | 8～60台のドライブ | 8～60台のドライブ | 8～60台のドライブ 


2+| HDD（SAS、NL-SAS、SATA） | 該当なし | 4～60台のドライブ | 4～60台のドライブ 


2+| SSD（SAS） | 該当なし | 4～60ドライブ（SSDのみ） | 4～60ドライブ（SSDのみ） 


2+| ソフトウェア RAID を備えたローカル DAS | 該当なし | 該当する | 4～14 ドライブ（NVMe のみ） 


2+| 外部配列 ^1^ 3+| 外部アレイにホストされるデータストアは、FC、FCoE、iSCSI、NFS（KVMではNFSはサポートされていません）を介して接続されます。これらのデータストアは、高い可用性と耐障害性を提供します。 
|===
^1^ 外部アレイ プロトコルのサポートは、ネットワーク ストレージの接続を反映します。

--
.ソフトウェア
--
[cols="5"30"]
|===


2+| ソフトウェアの種類 3+| 説明 


2+| ハイパーバイザーのサポート (VMware) 3+| VMware vSphere 9.0 VMware vSphere 8.0GA およびアップデート 1 ～ 3 VMware vSphere 7.0GA およびアップデート 1 ～ 3C 


2+| ハイパーバイザーサポート (KVM)  a| 
Red Hat Enterprise Linux (RHEL) 64-bit (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.8、8.7、および 8.6

Rocky Linux (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7、8.6

*注*: RHEL 10.1および10.0、Rocky Linux 10.1および10.0ホスト上のKVMハイパーバイザーには、ソフトウェアRAIDワークフローの制限があります。詳細については、以下のナレッジベースの記事をご覧ください：

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020: ONTAP Select Deploy: RHEL 10 および ROCKY 10 を使用してクラスタ HWR を作成中に警告メッセージが表示される"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025: ONTAP Select DeployGUI: RHEL10/Rocky 10 を搭載したホスト上のクラスタ作成ページで、SWR のストレージ プールとストレージ ディスクが表示されない"^]




2+| 管理ソフトウェア 3+| NetApp Active IQ Unified Manager管理スイートONTAP Select Deploy Utility SnapCenter (オプション) 
|===
--
====
.関連情報
* link:concept_lic_production.html["容量層と容量プールのライセンスの種類について学ぶ"]

