---
sidebar: sidebar 
permalink: concept_terminology.html 
keywords: terminology, key concepts, concepts 
summary: ONTAP Select の調査と導入の計画を開始するときは、まず用語と主要な概念を理解しておくと役立ちます。 
---
= ONTAP Selectの用語と主要概念
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の調査と導入の計画を開始するときは、まず用語と主要な概念を理解しておくと役立ちます。

ONTAP Select Deploy:: ONTAP Select Deployは、ONTAP Selectクラスタの導入に使用する管理ユーティリティです。Deployユーティリティは専用のLinux仮想マシンで実行されます。Deployユーティリティには、Webユーザインターフェイス、CLI管理シェル、REST APIからアクセスできます。
カーネルベースの仮想マシン:: カーネルベース仮想マシン（KVM）は、Linuxカーネルの仮想化機能であり、ハイパーバイザープラットフォームとして機能します。幅広いゲストオペレーティングシステムがサポートされています。
ハイパーバイザーホストとONTAP Selectノード:: _ハイパーバイザーホスト_は、 ONTAP Select仮想マシンをホストするコアハードウェアプラットフォームです。ONTAPONTAP Select仮想マシンがハイパーバイザーホストに導入され、アクティブになると、_ONTAP Selectノード_とみなされます。
ONTAP Selectクラスタ:: 1、2、4、6、または8ノードで構成される_ONTAP Selectクラスタ_を作成できます。マルチノードクラスタには、常に1つ以上のHAペアが含まれます。例えば、4ノードクラスタは2つのHAペアで構成されます。シングルノードクラスタではHA機能は提供されません。
ハイパーバイザーホスト環境の準備:: Deploy管理ユーティリティを使用してONTAP Selectクラスタを導入する前に、 ONTAP Selectを実行するハイパーバイザーホスト（ストレージ環境とネットワーク環境を含む）を準備する必要があります。このホストの事前設定は、現在の要件と制限に基づいて、 ONTAP Select製品の外部で行われます。
評価と本番環境への導入:: すべてのONTAP Selectノードは、_評価ライセンス_または_購入ライセンス_のいずれかで実行されます。評価ライセンスを使用すると、本番環境に導入する前にONTAP Selectを評価できます。評価ライセンスは自動的に生成され、適用されます。本番環境にクラスタを導入する場合は、ライセンスを購入する必要があります。ライセンスを購入する際には、以下の項目を選択してください。
+
--
* ライセンスモデル
* ストレージ容量
* プラットフォームライセンスの提供


--
容量階層ライセンスモデル:: キャパシティ・ティア・ライセンスモデルは、 ONTAP Select環境のストレージライセンス取得におけるオリジナルのオプションです。これは、 NetApp AFFおよびFASで使用されるONTAPモデルに基づいています。ノードごとに個別のライセンスが必要です。ストレージ容量はノードにロックされ、永続的（更新不要）です。
容量プールのライセンスモデル:: 容量プールのライセンスモデルは、Deploy 2.10を使用してONTAP Select 9.5で導入されました。ストレージ容量プールごとに個別のライセンスが必要です。容量プールのライセンスは、License Managerインスタンス（つまりDeployインスタンス）にロックされており、購入時の条件に基づいて更新する必要があります。組織内では、任意の数の容量プールのライセンスを取得して使用できます。ただし、容量プールはONTAP Selectノード間で共有されるため、通常、必要なライセンス数は容量階層ライセンスよりも少なくなります。
ライセンスマネージャー:: ライセンスマネージャは、容量プールライセンスをサポートするソフトウェアコンポーネントです。現在、Deploy管理ユーティリティの一部です。LMは、管理対象の共有プールからONTAP Selectノードにストレージをリースします。ライセンスロックID（License Lock ID）は、各LMインスタンス（つまり各Deployインスタンス）を一意に識別する数値文字列です。ライセンスファイルを生成するには、容量プールライセンスのシリアル番号とLLIDの両方を使用する必要があります。
プラットフォームライセンスの提供:: ライセンスを購入すると、 ONTAP Select仮想マシンのサイズ機能を決定する 3 つのライセンス オファリングが利用可能です。
+
--
* Standard
* Premium
* プレミアムXL


--


詳細については、「プラン」と「ライセンス」の 2 つのセクションを参照してください。

ストレージプールとデータストア:: ONTAP Select の_ストレージプール_ は、基盤となる物理ストレージを抽象化して隠蔽するように設計された論理データコンテナです。ストレージプールはハイパーバイザーに依存しません。ESXiハイパーバイザーホストに導入された場合、 ONTAP Selectストレージプールは VMware の _データストア_ と同義になります。
クラスターMTU:: クラスタMTUは、 ONTAP Selectマルチノードクラスタで使用される内部ネットワークで使用されるMTUサイズを設定できる機能です。Deploy管理ユーティリティは、HAペアの設定に応じて、ネットワーク環境に合わせてMTUサイズを調整します。手動で値を設定することもできます。
ONTAP SelectvNAS:: ONTAP Select vNASソリューションにより、 ONTAP Selectノードは外部ストレージ上のVMwareデータストアにアクセスできます。ONTAPONTAP Select vNASでは、ローカルRAIDコントローラは不要になり、RAID機能はリモートストレージによって提供されるものと想定されます。ONTAPONTAP Select vNASは、以下の方法で構成できます。
+
--
* VMware vSAN
* 汎用外部ストレージアレイ


--


どちらの場合も、 ONTAP Selectクラスタを作成する前、または既存のノードのストレージ容量を拡張する前に、外部ストレージを設定する必要があります。

ESXi VM上のノードの再ホスティング:: ONTAP Select vNAS ソリューション（VMware vSAN または汎用外部ストレージ アレイ）を通じて利用可能な外部ストレージを使用するクラスタを展開する場合、 ONTAP Selectノードをホストしている ESXi 仮想マシンは、次の VMware 機能を利用したアクションを通じて移動できます。
+
--
* vMotion
* 高可用性（HA）
* Distributed Resource Scheduler（DRS）
+
ONTAP Select Deploy ユーティリティは、次のようなクラスタでの操作実行の一環として仮想マシンの移動を検出します。

* クラスターオンライン
* クラスターがオフライン
* ストレージ追加
+
仮想マシンを移動すると、Deployユーティリティは内部データベースを更新し、新しいESXiホストを構成します。仮想マシンの移動とDeployの更新が完了するまで、 ONTAP Selectノードで実行されるすべてのアクションはブロックされます



--
KVM用のOpen vSwitch:: Open vSwitch (OVS) は、複数のネットワークプロトコルをサポートする仮想スイッチのソフトウェア実装です。OVSはオープンソースであり、Apache License 2.0 に基づいて利用可能です。
仲介サービス:: ONTAP Select Deployユーティリティには、アクティブな2ノードクラスタ内のノードに接続するメディエーターサービスが含まれています。このサービスは各HAペアを監視し、障害管理を支援します。



CAUTION: アクティブな2ノードクラスタが1つ以上ある場合、クラスタを管理するONTAP Select Deploy仮想マシンは常に実行されている必要があります。Deploy仮想マシンが停止すると、メディエーターサービスが利用できなくなり、2ノードクラスタのHA機能が失われます。

MetroCluster SDS:: MetroCluster SDSは、2ノードのONTAP Selectクラスタを導入する際に追加の構成オプションを提供する機能です。一般的な2ノードROBO導入とは異なり、 MetroCluster SDSノード間の距離を大幅に離すことができます。この物理的な分離により、ディザスタリカバリなどの新たなユースケースが可能になります。MetroClusterSDSを使用するには、Premiumライセンス以上が必要です。また、ノード間のネットワークは、最小レイテンシ要件を満たしている必要があります。
資格情報ストア:: デプロイ認証情報ストアは、アカウント認証情報を保持するセキュアなデータベースです。主に、新規クラスター作成の一環としてハイパーバイザーホストを登録するために使用されます。詳細については、「計画」セクションをご覧ください。
ストレージ効率:: ONTAP Selectは、 FASおよびAFFアレイに搭載されているストレージ効率オプションと同様のストレージ効率オプションを提供します。概念的には、DAS（直接接続ストレージ）SSD（プレミアムライセンスを使用）を使用したONTAP Selectは、 AFFアレイに類似しています。HDDを使用したDAS構成およびすべてのvNAS構成は、 FASアレイに類似していると考える必要があります。2つの構成の主な違いは、DAS SSDを使用したONTAP Selectが、アグリゲートレベルのインライン重複排除とアグリゲートレベルのバックグラウンド重複排除をサポートしていることです。残りのストレージ効率オプションは、どちらの構成でも利用できます。
+
--
vNASのデフォルト設定では、シングルインスタンスデータロギング（SIDL）と呼ばれる書き込み最適化機能が有効になっています。ONTAPONTAP Select 9.6以降のリリースでは、SIDLが有効になっている状態でもバックグラウンドのONTAPストレージ効率機能が動作することが確認されています。詳細については、「詳細」セクションをご覧ください。

--
クラスターの更新:: クラスタを作成した後、 ONTAPまたはハイパーバイザ管理ツールを使用して、Deployユーティリティの外部からクラスタまたは仮想マシンの構成を変更できます。また、仮想マシンを移行して構成を変更することも可能です。これらの変更が発生すると、Deployユーティリティは自動的に更新されず、クラスタの状態と同期しなくなる可能性があります。クラスタ更新機能を使用して、Deploy構成データベースを更新できます。クラスタ更新は、DeployのWebユーザーインターフェース、CLI管理シェル、およびREST APIから実行できます。
ソフトウェアRAID:: 直接接続ストレージ（DAS）を使用する場合、RAID機能は従来、ローカルのハードウェアRAIDコントローラによって提供されます。代わりに、ノードをソフトウェアRAIDを使用するように設定し、 ONTAP SelectノードがRAID機能を提供するようにすることもできます。ソフトウェアRAIDを使用する場合、ハードウェアRAIDコントローラは不要になります。


[[ontap-select-image-install]]
ONTAP Selectイメージのインストール:: Deploy 管理ユーティリティには、 ONTAP Selectの 1 つのバージョンのみが含まれています。含まれるバージョンは、リリース時点で利用可能な最新バージョンです。ONTAPONTAP Selectイメージインストール機能を使用すると、以前のバージョンのONTAP SelectをDeployユーティリティのインスタンスに追加できます。これにより、 ONTAP Selectクラスタの導入時に使用できるようになります。見るlink:task_cli_deploy_image_add.html["詳細については、 ONTAP Selectイメージを追加してください。"]。



NOTE: Deployインスタンスに含まれている元のバージョンよりも前のバージョンのONTAP Selectイメージのみを追加してください。Deployを更新せずに、新しいバージョンのONTAP Selectを追加することはサポートされていません。

ONTAP Selectクラスタの導入後の管理:: ONTAP Selectクラスタを導入したら、ハードウェアベースのONTAPクラスタと同様にクラスタを設定できます。たとえば、System Managerまたは標準のONTAPコマンドラインインターフェイスを使用してONTAP Selectクラスタを設定できます。


.関連情報
link:task_cli_deploy_image_add.html["ONTAP Selectイメージをデプロイに追加する"]
