---
sidebar: sidebar 
permalink: concept_usecase_overview.html 
keywords: ontap select, business use case overview, deployment, storage, development and testing 
summary: ONTAP Select は、ハイパーバイザー仮想化によって提供される固有の柔軟性に基づいて、さまざまな種類のアプリケーションに適しています。 
---
= ONTAP Selectのビジネスニーズと使用シナリオ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select は、ハイパーバイザー仮想化によって提供される固有の柔軟性に基づいて、さまざまな種類のアプリケーションに適しています。



== 導入

大まかに言えば、ハイパーバイザー ホスト サーバ上のワークロードに関して、 ONTAP Select を2 つの異なる方法で導入できます。



=== 専用展開

専用導入モデルでは、ホストサーバ上でONTAP Selectのインスタンスが1つだけ実行されます。同じハイパーバイザーホスト上では、他の重要な処理は実行されません。



=== 共存展開

コロケーション導入モデルでは、 ONTAP Selectは他のワークロードとホストを共有します。具体的には、通常はコンピューティングアプリケーションを実行する追加の仮想マシンが存在します。これらのコンピューティングワークロードは、 ONTAP Selectクラスタに対してローカルです。このモデルは、特殊なアプリケーションと導入要件をサポートします。専用導入モデルと同様に、各ONTAP Select仮想マシンは、それぞれ専用のハイパーバイザーホスト上で実行する必要があります。



== ストレージ

ONTAP Select は、ビジネス ニーズに応じて、プライマリ ストレージまたはセカンダリ ストレージとして使用できます。



=== プライマリ ストレージ

場合によっては、 ONTAP Selectをプライマリストレージプラットフォームとして導入することを選択することもあります。こうした実装方法は多様であり、アプリケーションのワークロード特性やビジネス目標によって異なります。



=== 災害復旧と二次ストレージ

ONTAP Selectを使用すると、プライマリストレージの機能を拡張する追加ストレージを実装できます。追加ストレージは、組織のディザスタリカバリやデータバックアップ計画をサポートするために使用できます。



== 開発とテスト

組織内に様々なアプリケーションを導入する際には、 ONTAP Selectをアプリケーション開発およびテストプロセス全体の不可欠な要素として活用できます。例えば、テストの入力データや出力データを保持するための一時的なストレージが必要になる場合があります。こうした導入期間の長さは、アプリケーションの特性や要件によって異なります。
