---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: ONTAP Select Deployは、 ONTAP Selectクラスタの導入と管理に使用する管理ユーティリティです。Deploy 
---
= ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deployは、 ONTAP Selectクラスタの導入と管理に使用する管理ユーティリティです。DeployはLinux仮想マシンとしてパッケージ化されており、 ONTAP Selectクラスタを作成する前にインストールする必要があります。



== コア機能

デプロイ管理ユーティリティは、次のコア機能を実行します。

* ONTAP Selectが導入されている各ハイパーバイザーホストの詳細を記録します。
* ホストを構成し、必要なライセンスをインストールする
* ONTAP Selectクラスタの導入と管理
* ONTAP Selectクラスタとホストのインベントリを維持する
* AutoSupportデータを収集してNetAppに送信する
* ONTAP Selectノードイメージの内部セットを維持する
* ハイパーバイザー固有のコマンド形式とプロトコルをサポートする




== デプロイユーティリティにアクセスする方法

Deploy管理ユーティリティへのアクセスには、いくつかのオプションがあります。すべての外部インターフェースは機能的に同等です。導入の目標と要件に最適なアクセスオプションを選択してください。いずれの場合も、有効なパスワードを持つ管理者アカウントを使用してサインインしてください。



=== Webグラフィカルユーザーインターフェース

デプロイユーティリティには、最新のWebブラウザからアクセスできます。WebUIは直感的で使いやすいインターフェースを提供し、ほとんどの場合、ユーティリティを使用する際の主要なインターフェースとなります。



=== コマンドライン インターフェイス

管理シェルを通じて、テキストベースのコマンドラインインターフェースを利用できます。CLI管理シェルには、以下の方法でアクセスできます。

* セキュアシェル（SSH）
* 仮想マシンコンソール


通常、仮想マシンコンソールはインストールと初期設定プロセスの一部として使用されます。ただし、ほとんどの場合、SSHの方がより柔軟で便利なオプションとなります。



=== REST ウェブサービス API

外部クライアントに公開される REST Web サービス API は、デプロイ ユーティリティに接続するときに別のオプションを提供します。このAPIには、REST Webサービスをサポートする主なプログラミング言語やツールを使用してアクセスできます。広く利用されているプログラミング言語およびツールは次のとおりです。

* Python
* Java
* Curl


プログラミング言語またはスクリプト言語を使用すると、 ONTAP Selectクラスタの導入と管理を自動化できます。



=== ONTAP SelectオンラインドキュメントWebページ

デプロイユーティリティでオンラインドキュメントのウェブページを表示することは、REST WebサービスAPIにアクセスする別の方法です。ただし、プログラミング言語を使用する代わりに、ブラウザを使用してページから管理APIにアクセスします。以下の機能が提供されます。

* REST WebサービスAPIのすべての呼び出しの詳細な説明
* API呼び出しを手動で発行する機能


Deploy仮想マシンのIPアドレスまたはドメイン名を使用して、オンラインドキュメントページにアクセスできます。ページを表示するには、ブラウザに次の形式の URL を入力します (Deploy VM インスタンスの適切な IP アドレスまたはドメイン名に置き換えます)。 `\http://<ip_address>/api/ui`
