---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: まず、 ONTAP Select環境に適用される一般的なネットワーク概念を理解しましょう。次に、シングルノードクラスタとマルチノードクラスタで利用可能な具体的な特性とオプションについて説明します。 
---
= ONTAP Selectネットワークの概念と特徴
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
まず、 ONTAP Select環境に適用される一般的なネットワーク概念を理解しましょう。次に、シングルノードクラスタとマルチノードクラスタで利用可能な具体的な特性とオプションについて説明します。



== 物理ネットワーク

物理ネットワークは、主に基盤となるレイヤー2スイッチングインフラストラクチャを提供することで、 ONTAP Selectクラスタの導入をサポートします。物理ネットワークに関連する構成には、ハイパーバイザーホストと、より広範なスイッチネットワーク環境の両方が含まれます。



=== ホストNICオプション

各ONTAP Selectハイパーバイザーホストは、2つまたは4つの物理ポートで構成する必要があります。具体的な構成は、以下の要因などによって異なります。

* クラスタに1つのONTAP Selectホストが含まれているか、複数のONTAP Selectホストが含まれているか
* 使用されているハイパーバイザーオペレーティングシステム
* 仮想スイッチの構成方法
* リンクでLACPが使用されているかどうか




=== 物理スイッチの構成

物理スイッチの構成がONTAP Selectの導入環境をサポートしていることを確認する必要があります。物理スイッチはハイパーバイザーベースの仮想スイッチと統合されています。具体的な構成は、いくつかの要因によって異なります。主な考慮事項は次のとおりです。

* 内部ネットワークと外部ネットワークの分離をどのように維持しますか?
* データ ネットワークと管理ネットワーク間の分離を維持しますか?
* レイヤー 2 VLAN はどのように構成されますか?




== 論理ネットワーク

ONTAP Selectは2つの異なる論理ネットワークを使用し、トラフィックをタイプに応じて分離します。具体的には、トラフィックはクラスタ内のホスト間だけでなく、クラスタ外のストレージクライアントやその他のマシンにも流れます。ハイパーバイザーによって管理される仮想スイッチは、論理ネットワークをサポートします。



=== 内部ネットワーク

マルチノードクラスタ環境では、個々のONTAP Selectノードは分離された「内部」ネットワークを使用して通信を行います。このネットワークは、ONTAP Selectクラスタ内のノードの外部には公開されず、利用できません。


NOTE: 内部ネットワークは、マルチノード クラスターの場合にのみ存在します。

内部ネットワークには次の特性があります。

* 次のものを含むONTAPクラスタ内トラフィックを処理するために使用されます。
+
** クラスタ
** 高可用性相互接続 (HA-IC)
** RAID 同期ミラー (RSM)


* VLAN に基づく単一のレイヤ 2 ネットワーク
* 静的 IP アドレスはONTAP Selectによって割り当てられます。
+
** IPv4のみ
** DHCPは使用されません
** リンクローカルアドレス


* MTU サイズはデフォルトで 9000 バイトですが、7500 から 9000 までの範囲で調整できます。




=== 外部ネットワーク

外部ネットワークは、 ONTAP Selectクラスタのノードと外部ストレージクライアント、および他のマシン間のトラフィックを処理します。外部ネットワークはすべてのクラスタ環境の一部であり、次のような特徴があります。

* 次のONTAPトラフィックを処理するために使用されます:
+
** データ (NFS、CIFS、iSCSI)
** 管理（クラスタとノード、オプションでSVM）
** クラスター間（オプション）


* オプションでVLANをサポート:
+
** データポートグループ
** 管理ポートグループ


* 管理者の構成選択に基づいて割り当てられる IP アドレス:
+
** IPv4またはIPv6


* MTU サイズはデフォルトで 1500 バイトです (調整可能)


外部ネットワークには、あらゆるサイズのクラスターが存在します。



== 仮想マシンネットワーク環境

ハイパーバイザー ホストは、いくつかのネットワーク機能を提供します。

ONTAP Select は、仮想マシンを通じて公開される次の機能に依存します。

仮想マシンポート:: ONTAP Selectで使用できるポートは複数あります。これらのポートは、クラスタのサイズなど、いくつかの要因に基づいて割り当てられ、使用されます。
仮想スイッチ:: ハイパーバイザー環境内の仮想スイッチソフトウェア（vSwitch（VMware）またはOpen vSwitch（KVM））は、仮想マシンによって公開されるポートと物理イーサネットNICポートを接続します。環境に応じて、すべてのONTAP SelectホストにvSwitchを設定する必要があります。

