---
sidebar: sidebar 
permalink: concept_lic_cp_serial_number.html 
keywords: license, licensing, Capacity Pools, node serial numbers 
summary: キャパシティ・ティア・ライセンスモデルでは、9桁のノードシリアル番号は、ノードに割り当てられたライセンスシリアル番号と同じです。ただし、キャパシティ・プール・ライセンスモデルを使用するノードに割り当てられるシリアル番号の形式は異なります。 
---
= ONTAP Select容量プール ライセンス モデルのノード シリアル番号
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
キャパシティ・ティア・ライセンスモデルでは、9桁のノードシリアル番号は、ノードに割り当てられたライセンスシリアル番号と同じです。ただし、キャパシティ・プール・ライセンスモデルを使用するノードに割り当てられるシリアル番号の形式は異なります。

容量プール ライセンスを使用するノードのシリアル番号の形式は次のとおりです。

`999 ppppppppp nnnnnnnn`


NOTE: わかりやすくするためにスペースが追加されていますが、実際のシリアル番号の一部ではありません。

ノードシリアル番号の各セクションについては、次の表で左から右の順に説明します。

[cols="15,85"]
|===
| セクション | 説明 


| 「999」 | NetAppによって予約されている 3 桁の定数値。 


| ぷぷぷぷぷ | NetAppによって容量プールに割り当てられた 9 桁の可変ライセンス シリアル番号 


| んんんんん | 容量プールを使用する各ノードに対してライセンス マネージャーによって生成される 8 桁の可変値 
|===

NOTE: 注意： NetAppサポートにCapacity Poolライセンスを使用するノードに関するケースをオープンする場合、20桁のノードシリアル番号全体を提供することはできません。代わりに、9桁のCapacity Poolライセンスシリアル番号を提供する必要があります。上記のように、ノードシリアル番号からライセンスシリアル番号を導き出すことができます。ノードシリアル番号の最初の3桁（「999」）をスキップし、次の9桁（pppppppppp）を抽出します。
