---
sidebar: sidebar 
permalink: concept_api_before_workflows.html 
keywords: rest api, deploy rest api, rest, workflows, before you begin 
summary: ワークフロー プロセスを確認して使用するための準備をする必要があります。 
---
= ONTAP Select Deploy APIワークフローを使用する前に
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ワークフロー プロセスを確認して使用するための準備をする必要があります。



== ワークフローで使用されるAPI呼び出しを理解する

ONTAP Selectのオンラインドキュメントページには、すべてのREST API呼び出しの詳細が記載されています。ここではそれらの詳細を繰り返すのではなく、ワークフローサンプルで使用されている各API呼び出しには、ドキュメントページで呼び出しを見つけるために必要な情報のみが記載されています。特定のAPI呼び出しを見つけたら、入力パラメータ、出力形式、HTTPステータス コード、要求処理のタイプなど、呼び出しの詳細を確認できます。

ワークフローで使用している各API呼び出しについて、ドキュメント ページで見つけるのに役立つように次の情報を示します。

* カテゴリ API 呼び出しは、ドキュメント ページ上で機能的に関連する領域またはカテゴリに整理されています。特定のAPI呼び出しを見つけるには、ページの一番下までスクロールし、該当するAPIカテゴリをクリックします。
* HTTP 動詞 HTTP 動詞は、リソースに対して実行されるアクションを識別します。各API呼び出しは、単一のHTTP動詞を使用して実行されます。
* パス パスは、呼び出しの実行の一部としてアクションが適用される特定のリソースを決定します。コアのURLのあとにパス文字列を追加することで、リソースを識別する完全なURLが形成されます。




== REST APIに直接アクセスするためのURLを構築する

ONTAP Selectのドキュメントページに加えて、Pythonなどのプログラミング言語を使用してDeploy REST APIに直接アクセスすることもできます。この場合、コアURLはオンラインドキュメントページにアクセスする際のURLと若干異なります。APIに直接アクセスする場合は、ドメインとポートの文字列に「/api」を追加する必要があります。例えば：
`\http://deploy.mycompany.com/api`
