---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: RESTで共通のテクノロジとベストプラクティスは確立されますが、各APIの詳細は設計内容に応じて異なる場合があります。API を使用する前に、 ONTAP Select Deploy API の詳細と動作特性を理解しておく必要があります。 
---
= ONTAP Select Deploy API の基本的な動作特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
RESTで共通のテクノロジとベストプラクティスは確立されますが、各APIの詳細は設計内容に応じて異なる場合があります。API を使用する前に、 ONTAP Select Deploy API の詳細と動作特性を理解しておく必要があります。



== ハイパーバイザーホストとONTAP Selectノード

_ハイパーバイザーホスト_は、 ONTAP Select仮想マシンをホストするコアハードウェアプラットフォームです。ONTAPONTAP Select仮想マシンがハイパーバイザーホストに導入され、アクティブになると、その仮想マシンは_ONTAP Selectノード_とみなされます。DeployREST APIバージョン3では、ホストオブジェクトとノードオブジェクトは別個の独立したオブジェクトです。これにより、1対多の関係が可能になり、1つ以上のONTAP Selectノードを同じハイパーバイザーホスト上で実行できます。



== オブジェクトID

リソース インスタンスまたはオブジェクトには、作成時に一意の識別子がそれぞれ割り当てられます。これらの識別子は、 ONTAP Select Deployの特定のインスタンス内でグローバルに一意です。新しいオブジェクトインスタンスを作成するAPI呼び出しを発行した後、関連付けられたID値が呼び出し元に返されます。 `location` HTTP 応答のヘッダー。リソース インスタンスを以降の呼び出しで参照する際は、この識別子を抽出して使用できます。


NOTE: オブジェクト識別子の内容と内部構造は変更になることがあります。識別子を使用するのは、該当するAPI呼び出しで関連付けられているオブジェクトを参照するために必要な場合だけにしてください。



== リクエスト識別子

成功したAPIリクエストにはそれぞれ固有の識別子が割り当てられます。識別子は `request-id`関連する HTTP 応答のヘッダー。リクエストIDを使用すると、特定のAPIリクエスト・レスポンス・トランザクションのアクティビティをまとめて参照できます。例えば、リクエストIDに基づいて、あるトランザクションのすべてのイベントメッセージを取得できます。



== 同期呼び出しと非同期呼び出し

サーバーがクライアントから受信した HTTP 要求を実行する主な方法は 2 つあります。

* 同期 サーバーは要求を直ちに実行し、ステータス コード 200、201、または 204 で応答します。
* 非同期：サーバーはリクエストを受け入れ、ステータスコード202で応答します。これは、サーバーがクライアントからのリクエストを受け入れ、リクエストを完了するためのバックグラウンドタスクを開始したことを示します。最終的な成功または失敗はすぐには確認できず、追加のAPI呼び出しを通じて判断する必要があります。




== 長時間実行ジョブの完了を確認する

通常、完了までに長時間かかる操作は、サーバー側でバックグラウンドタスクを使用して非同期的に処理されます。DeployREST APIでは、すべてのバックグラウンドタスクはジョブオブジェクトによってアンカーされ、このオブジェクトはタスクを追跡し、現在の状態などの情報を提供します。バックグラウンドタスクが作成されると、一意の識別子を含むジョブオブジェクトがHTTPレスポンスで返されます。

ジョブオブジェクトを直接クエリすることで、関連するAPI呼び出しの成功または失敗を確認できます。詳細については、「ジョブオブジェクトを使用した非同期処理」を参照してください。

Job オブジェクトを使用する以外にも、次のような方法でリクエストの成功または失敗を判断できます。

* イベントメッセージ 元のレスポンスで返されたリクエストIDを使用して、特定のAPI呼び出しに関連付けられたすべてのイベントメッセージを取得できます。イベントメッセージには通常、成功または失敗の情報が含まれ、エラー状態のデバッグにも役立ちます。
* リソースの状態またはステータス リソースのいくつかは状態またはステータス値を維持しており、これを照会することで、要求の成功または失敗を間接的に判断できます。




== セキュリティ

Deploy API は次のセキュリティ テクノロジを使用します。

* トランスポート層セキュリティ（TLS） デプロイサーバーとクライアント間のネットワーク上で送信されるすべてのトラフィックは、TLSによって暗号化されます。暗号化されていないチャネルでのHTTPプロトコルの使用はサポートされていません。TLSバージョン1.2がサポートされています。
* HTTP認証：すべてのAPIトランザクションには基本認証が使用されます。ユーザー名とパスワードをBase64文字列で含むHTTPヘッダーがすべてのリクエストに追加されます。

