---
settings:
  name: ONTAP Select
  harmony_integration: maestro
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: 9.17.1
    url: "/ontap-select-9171"
  - version-number: 9.18.1
    url: "/ontap-select"
  - version-number: 9.16.1
    url: "/ontap-select-9161"
  - version-number: 9.15.1
    url: "/ontap-select-9151"
  - version-number: 9.14.1
    url: "/ontap-select-9141"
  - version-number: 9.13.1
    url: "/ontap-select-9131"
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP Select 9.17.1 ドキュメント
    url: "/index.html"
  - title: リリース ノート
    entries:
    - title: ONTAP Selectリリースノート
      url: "/reference_release_notes.html"
    - title: 新機能
      url: "/reference_new_ots.html"
  - title: 概念
    entries:
    - title: ONTAP Selectについて学ぶ
      url: "/concept_ots_overview.html"
    - title: ONTAP Select Deploy
      url: "/concept_ots_deploy.html"
    - title: ビジネスユースケース
      entries:
      - title: ビジネスニーズと使用シナリオ
        url: "/concept_usecase_overview.html"
      - title: リモートオフィスとブランチオフィス
        url: "/concept_usecase_robo.html"
      - title: プライベートクラウドとデータセンター
        url: "/concept_usecase_private_cloud.html"
      - title: データ保護と効率
        url: "/concept-data-protection-and-efficiency.html"
    - title: 用語
      url: "/concept_terminology.html"
  - title: Plan
    entries:
    - title: 展開ワークフロー
      url: "/concept_workflow_deploy.html"
    - title: ONTAP Select
      entries:
      - title: 一般要件
        url: "/reference_plan_ots_general.html"
      - title: ハイパーバイザーとハードウェア
        url: "/reference_plan_ots_hardware.html"
      - title: ストレージとRAID
        url: "/reference_plan_ots_storage.html"
      - title: 外部ストレージ要件
        entries:
        - title: VMware ESXi
          url: "/reference_plan_ots_vnas.html"
        - title: KVM
          url: "/reference_plan_ots_kvm.html"
      - title: ネットワーク
        url: "/reference_plan_ots_networking.html"
      - title: 2ノードクラスタ
        url: "/reference_plan_ots_two_node.html"
      - title: リモートオフィスとブランチオフィス
        url: "/reference_plan_ots_robo.html"
      - title: MetroCluster SDS
        url: "/reference_plan_ots_mcc_sds.html"
      - title: ESXi 上の VMware vCenter
        url: "/reference_plan_ots_vcenter.html"
    - title: ONTAP Select Deploy
      entries:
      - title: 一般要件
        url: "/reference_plan_dep_general.html"
      - title: VMware環境
        url: "/reference_plan_dep_vmware.html"
    - title: ベストプラクティス
      url: "/reference_plan_best_practices.html"
  - title: ライセンス
    entries:
    - title: オプション
      entries:
      - title: 評価ライセンス
        url: "/concept_lic_evaluation.html"
      - title: 生産ライセンス
        url: "/concept_lic_production.html"
      - title: プラットフォームライセンスの提供
        url: "/concept_lic_platforms.html"
    - title: 容量プールのライセンスモデル
      entries:
      - title: 運用の詳細
        url: "/concept_lic_cp_operation.html"
      - title: ノードのシリアル番号
        url: "/concept_lic_cp_serial_number.html"
      - title: 制限事項
        url: "/concept_lic_cp_restrictions.html"
      - title: 容量プールと容量階層
        url: "/concept_lic_cp_compare_ct.html"
      - title: メリットの概要
        url: "/concept_lic_cp_benefits.html"
    - title: 購入
      entries:
      - title: ライセンスワークフロー
        url: "/concept_lic_workflow.html"
      - title: 容量階層
        url: "/task_lic_acquire_ct.html"
      - title: 容量プール
        url: "/task_lic_acquire_cp.html"
    - title: ONTAPの機能
      url: "/reference_lic_ontap_features.html"
  - title: インストール
    entries:
    - title: インストール前のチェックリスト
      entries:
      - title: ホスト準備チェックリスト
        entries:
        - title: KVMホストのチェックリスト
          url: "/kvm-host-configuration-and-preparation-checklist.html"
        - title: ESXi ホストのチェックリスト
          url: "/esxi-host-configuration-and-preparation-checklist.html"
      - title: デプロイユーティリティに必要な情報
        url: "/reference_chk_deploy_req_info.html"
      - title: ONTAP Selectに必要な情報
        url: "/reference_chk_select_req_info.html"
      - title: NVMeホスト構成
        url: "/task_chk_nvme_configure.html"
    - title: ONTAP Select Deploy をインストールする
      url: "/task_install_deploy.html"
    - title: クラスターを展開する
      url: "/task_deploy_cluster.html"
    - title: 初期クラスタ状態
      url: "/reference_initial_state.html"
  - title: 管理する
    entries:
    - title: 開始する前に
      url: "/concept_adm_before.html"
    - title: ノードのアップグレード
      url: "/concept_adm_upgrading_nodes.html"
    - title: 診断とサポート
      url: "/task_adm_support.html"
    - title: セキュアONTAP Select
      url: "/task_adm_security.html"
    - title: ネットワーク接続を確認する
      url: "/task_adm_connectivity.html"
    - title: 仲介サービスの管理
      url: "/task_adm_mediators.html"
    - title: クラスタ
      entries:
      - title: ONTAP Selectクラスタ
        url: "/task_adm_clusters.html"
      - title: クラスターを拡大または縮小する
        url: "/task_cluster_expansion_contraction.html"
    - title: ノードとホスト
      entries:
      - title: VMビデオコンソールにアクセスする
        url: "/task_adm_video_console.html"
      - title: クラスターノードのサイズを変更する
        url: "/task_adm_resize.html"
      - title: 故障したソフトウェアRAIDドライブを交換する
        url: "/task_adm_replace_drives_swraid.html"
      - title: VMFS6へのアップグレード
        url: "/task_adm_upgrade_vmfs6.html"
    - title: ライセンス
      url: "/task_adm_licenses.html"
  - title: 深掘り
    entries:
    - title: ストレージ
      entries:
      - title: 一般的な概念と特徴
        url: "/concept_stor_concepts_chars.html"
      - title: ローカル接続ストレージ用のハードウェア RAID サービス
        url: "/concept_stor_hwraid_local.html"
      - title: ローカル接続ストレージ用のソフトウェア RAID サービス
        url: "/concept_stor_swraid_local.html"
      - title: VSANおよび外部アレイ構成
        url: "/concept_stor_vsan_external.html"
      - title: ストレージ容量を増やす
        url: "/concept_stor_capacity_inc.html"
      - title: ストレージ効率サポート
        url: "/concept_stor_eff_support.html"
    - title: ネットワーク
      entries:
      - title: 一般的な概念と特徴
        url: "/concept_nw_concepts_chars.html"
      - title: 単一ノードと複数ノードの構成
        url: "/concept_nw_single_multi_node.html"
      - title: 内部および外部ネットワーク
        url: "/concept_nw_internal_external.html"
      - title: サポートされている構成
        url: "/concept_nw_supported_configs.html"
      - title: VMware vSphere VSwitch 構成
        url: "/concept_nw_vsphere_vswitch_config.html"
      - title: 物理スイッチの構成
        url: "/concept_nw_physical_switch_config.html"
      - title: データと管理の分離
        url: "/concept_nw_data_mgmt_separation.html"
    - title: 高可用性アーキテクチャ
      entries:
      - title: HA構成
        url: "/concept_ha_config.html"
      - title: 同期レプリケーションとミラーリングされたアグリゲート
        url: "/concept_ha_mirroring.html"
      - title: その他の高可用性機能
        url: "/concept_ha_other.html"
    - title: パフォーマンス
      entries:
      - title: パフォーマンスの概要
        url: "/concept_perf_general.html"
      - title: ONTAP Select 9.6 のパフォーマンス
        url: "/concept_perf_premium_ha_direct_ssd_96.html"
  - title: RESTで自動化
    entries:
    - title: 概念
      entries:
      - title: REST Webサービス
        url: "/concept_api_rest.html"
      - title: デプロイAPIにアクセスする
        url: "/concept_api_how_access.html"
      - title: 基本操作
        url: "/concept_api_operation.html"
      - title: リクエストとレスポンスのトランザクション
        url: "/concept_api_transaction.html"
      - title: 非同期処理
        url: "/concept_api_async_proc.html"
    - title: ブラウザでアクセス
      entries:
      - title: 開始する前に
        url: "/concept_api_before_browser.html"
      - title: ドキュメントページにアクセスする
        url: "/task_api_access_doc_page.html"
      - title: API呼び出しを理解する
        url: "/task_api_understanding_call.html"
    - title: ワークフロープロセス
      entries:
      - title: 開始する前に
        url: "/concept_api_before_workflows.html"
      - title: ワークフロー1 クラスターを作成する
        url: "/reference_api_workflow01.html"
    - title: Pythonでアクセスする
      entries:
      - title: 開始する前に
        url: "/concept_api_before_python.html"
      - title: スクリプトを理解する
        url: "/concept_api_understanding_scripts.html"
    - title: Pythonコードサンプル
      entries:
      - title: クラスタを作成します。
        url: "/reference_api_script_cc.html"
      - title: クラスターを作成するためのJSON
        url: "/reference_api_json_cc.html"
      - title: ノードライセンスを追加する
        url: "/reference_api_script_anl.html"
      - title: クラスターを削除する
        url: "/reference_api_script_dc.html"
      - title: 共通サポートモジュール
        url: "/reference_api_script_common.html"
      - title: クラスターノードのサイズ変更
        url: "/reference_api_script_resize.html"
  - title: CLIを使用する
    entries:
    - title: SSHを使用してSign in
      url: "/task_cli_signing_in.html"
    - title: クラスターを展開する
      url: "/task_cli_deploy_cluster.html"
    - title: セキュリティ
      url: "/task_cli_security.html"
    - title: ネットワーク接続
      url: "/task_cli_connectivity.html"
    - title: クラスタ
      url: "/task_cli_clusters.html"
    - title: ノードとホスト
      entries:
      - title: ESXi のアップグレード
        url: "/cli-upgrade-esxi.html"
      - title: ホスト管理サーバーを変更する
        url: "/reference_host_modify_command.html"
    - title: デプロイユーティリティ
      entries:
      - title: デプロイインスタンスをアップグレードする
        url: "/task_cli_upgrade_deploy.html"
      - title: デプロイインスタンスの移行
        url: "/task_cli_migrate_deploy.html"
      - title: ONTAP Selectイメージを追加する
        url: "/task_cli_deploy_image_add.html"
      - title: ONTAP Selectイメージを削除する
        url: "/task_cli_deploy_image_remove.html"
      - title: 2ノードクラスタのRecover Deploy
        url: "/task_cli_deploy_recover_two_node.html"
  - title: クラスタの90日間評価インスタンスをデプロイする
    url: "/deploy-evaluation-ontap-select-ovf-template.html"
  - title: FAQ
    url: "/reference_faq.html"
  - title: 法律上の表示
    url: "/legal-notices.html"
