---
sidebar: sidebar 
permalink: reference_plan_ots_two_node.html 
keywords: plan, planning, two nodes, two node clusters 
summary: HA 構成の 2 ノード クラスタの導入には、他のクラスタ ノード構成と同様の計画と設定が必要です。ただし、2 ノード クラスタを作成する際には、いくつかの違いに注意する必要があります。 
---
= ONTAP Select 2ノードクラスタ（HA搭載）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HA 構成の 2 ノード クラスタの導入には、他のクラスタ ノード構成と同様の計画と設定が必要です。ただし、2 ノード クラスタを作成する際には、いくつかの違いに注意する必要があります。

.対象環境
2 ノード クラスターは 1 つの HA ペアで構成され、リモート オフィスおよびブランチ オフィスの展開用に特別に設計されています。


NOTE: 主にリモートおよびブランチ オフィス環境向けに設計されていますが、必要に応じてデータ センターに 2 ノード クラスターを展開することもできます。

.ライセンス
2ノードクラスタは、VMware vSphereライセンスを使用して導入できます。ただし、VMware ROBO StandardおよびAdvancedライセンスは、リモートオフィスやブランチオフィスへの導入に最適です。

.仲介サービス
クラスタが2つのノードで構成されている場合、ノードに障害が発生したり通信が途絶えたりすると、必要なクォーラムを達成できなくなります。このようなスプリットブレイン状態を解決するために、 ONTAP Select Deployユーティリティのすべてのインスタンスにはメディエータサービスが含まれています。このサービスは、アクティブな2ノードクラスタの各ノードに接続し、HAペアを監視して障害管理を支援します。メディエータサービスは、各2ノードクラスタに関連付けられた専用のiSCSIターゲットでHAの状態情報を維持します。


CAUTION: アクティブな2ノードクラスタが1つ以上ある場合、クラスタを管理するONTAP Select Deploy仮想マシンは常に実行されている必要があります。DeployONTAP Select Deploy 仮想マシンが停止または障害が発生した場合、メディエーター サービスは利用できなくなり、2 ノード クラスタの HA 機能が失われます。

.クラスターとメディエーターサービスの場所
2 ノード クラスタは通常、リモート オフィスまたはブランチ オフィスに導入されるため、企業のデータ センターや管理サポートを提供するONTAP Select Deploy ユーティリティから離れた場所に設置できます。この構成では、 ONTAP Select Deploy ユーティリティとクラスタ間の管理トラフィックは WAN 経由で流れます。制限事項の詳細については、リリースノートをご覧ください。

.デプロイ構成データをバックアップする
ベストプラクティスとしては、link:task_cli_clusters.html["ONTAP Select Deploy構成データをバックアップする"]クラスターの作成後も含め、定期的に実行します。これは、バックアップにメディエーター構成データが含まれるため、2ノードクラスターでは特に重要になります。

.デプロイに割り当てられた静的IPアドレス
ONTAP Select Deploy 管理ユーティリティに静的 IP アドレスを割り当てる必要があります。この要件は、1 つ以上のONTAP Select 2 ノード クラスタを管理するすべてのONTAP Select Deploy インスタンスに適用されます。
