---
sidebar: sidebar 
permalink: reference_plan_ots_networking.html 
keywords: plan, planning, networking, network, drivers, vmxnet3, cluster mtu, firewall 
summary: ONTAP Select を導入する前に、ハイパーバイザー ネットワークを正しく設定する必要があります。 
---
= ONTAP Selectネットワークの考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select を導入する前に、ハイパーバイザー ネットワークを正しく設定する必要があります。



== 仮想スイッチオプション

外部ネットワークと内部ネットワーク（マルチノードクラスタのみ）をサポートするには、各ONTAP Selectホストに仮想スイッチを設定する必要があります。マルチノードクラスタの導入の一環として、内部クラスタネットワークのネットワーク接続をテストする必要があります。


NOTE: ハイパーバイザーホスト上のvSwitchの設定方法と高速インターフェース機能の詳細については、link:concept_nw_concepts_chars.html["ディープダイブネットワーキング"]セクション。



== VMXNET3 へのアップグレード (ESXi のみ)

ONTAP Select 9.5（Deploy 2.10使用）以降、VMware ESXi上の新規クラスタデプロイメントには、VMXNET3がデフォルトのネットワークドライバとして含まれています。古いONTAP Selectノードをバージョン9.5以降にアップグレードしても、ドライバは自動的にアップグレードされません。



== クラスターMTU

マルチノードクラスタ内のONTAP Selectノードを接続するために、独立した内部ネットワークが使用されます。通常、このネットワークのMTUサイズは9000です。ただし、このMTUサイズではONTAP Selectノードを接続するネットワークには大きすぎる場合があります。より小さなフレームに対応するため、 ONTAP Selectが内部ネットワークで使用するMTUサイズは7500～9000バイトの範囲になります。

MTUサイズは、クラスタ作成ページの「クラスタの詳細」セクションに表示されます。この値は、Deploy管理ユーティリティによって以下のように決定されます。

. 初期デフォルトは 9000 です。
. HA ペアのホストとネットワークを追加すると、ネットワーク内の vSwitch の構成に基づいて、必要に応じて MTU 値が削減されます。
. クラスターの最終的なクラスター MTU 値は、すべての HA ペアを追加し、クラスターを作成する準備ができた後、設定されます。



NOTE: 必要に応じて、ネットワークの設計に基づいてクラスター MTU 値を手動で設定できます。



== 標準 vSwitch を備えた 2 つの NIC ホスト (ESXi のみ)

2つのNIC構成でONTAP Selectのパフォーマンスを向上させるには、2つのポートグループを使用して内部ネットワークトラフィックと外部ネットワークトラフィックを分離する必要があります。この推奨事項は、以下の特定の構成に適用されます。

* ONTAP Selectマルチノードクラスタ
* 2 つの NIC (NIC1 と NIC2)
* 標準vSwitch


この環境では、次のように 2 つのポート グループを使用してトラフィックを構成する必要があります。

.ポートグループ1
* 内部ネットワーク（クラスタ、RSM、HA-IC トラフィック）
* NIC1はアクティブです
* NIC2はスタンバイ状態


.ポートグループ2
* 外部ネットワーク（データおよび管理トラフィック）
* NIC1はスタンバイ状態
* NIC2がアクティブ


参照link:concept_nw_concepts_chars.html["ディープダイブネットワーキング"]2 つの NIC の展開の詳細については、「」セクションを参照してください。



== 標準 vSwitch を備えた 4 つの NIC ホスト (ESXi のみ)

4つのNIC構成でONTAP Selectのパフォーマンスを向上させるには、4つのポートグループを使用して内部ネットワークトラフィックと外部ネットワークトラフィックを分離する必要があります。この推奨事項は、以下の特定の構成に適用されます。

* ONTAP Selectマルチノードクラスタ
* 4 つの NIC (NIC1、NIC2、NIC3、NIC4)
* 標準vSwitch


この環境では、次の 4 つのポート グループを使用してトラフィックを構成する必要があります。

.ポートグループ1
* 内部ネットワーク（クラスタ、RSMトラフィック）
* NIC1はアクティブです
* NIC2、NIC3、NIC4はスタンバイ状態


.ポートグループ2
* 内部ネットワーク（クラスタ、HA-IC トラフィック）
* NIC3はアクティブです
* NIC1、NIC2、NIC4はスタンバイ状態


.ポートグループ3
* 外部ネットワーク（データおよび管理トラフィック）
* NIC2はアクティブです
* NIC1、NIC3、NIC4はスタンバイ状態


.ポートグループ4
* 外部ネットワーク（データトラフィック）
* NIC4はアクティブです
* NIC1、NIC2、NIC3はスタンバイ状態


参照link:concept_nw_concepts_chars.html["ディープダイブネットワーキング"]4 つの NIC の展開の詳細については、「」セクションを参照してください。



== ネットワークトラフィック要件

ONTAP Select導入環境内のさまざまな参加者間でネットワーク トラフィックが流れるように、ファイアウォールが適切に設定されていることを確認する必要があります。

.参加者
ONTAP Selectの導入環境において、ネットワークトラフィックを交換する複数の参加者またはエンティティが存在します。これらについては、ネットワークトラフィック要件の概要説明で紹介します。

* ONTAP Select Deploy管理ユーティリティの導入
* vSphere (ESXi のみ) クラスタ展開でホストがどのように管理されているかに応じて、vSphere サーバーまたは ESXi ホストのいずれかになります。
* ハイパーバイザーサーバー ESXi ハイパーバイザーホストまたは Linux KVM ホスト
* OTSノードONTAP Selectノード
* OTSクラスタONTAP Selectクラスタ
* 管理WS ローカル管理ワークステーション


.ネットワークトラフィック要件の概要
次の表は、ONTAP Select導入のネットワーク トラフィック要件を示しています。

[cols="20,20,35,25"]
|===
| プロトコル/ポート | ESXi / KVM | 送受信方向 | 説明 


| TLS (443) | ESXi | vCenter Server（管理対象）または ESXi（管理対象または非管理対象）にデプロイする | VMware VIX API 


| 902 | ESXi | vCenter Server（管理対象）またはESXi（管理対象外）にデプロイする | VMware VIX API 


| ICMP | ESXi または KVM | ハイパーバイザーサーバーに展開 | pingを実行します。 


| ICMP | ESXi または KVM | 各OTSノードに展開 | pingを実行します。 


| SSH (22) | ESXi または KVM | 各OTSノードへの管理WS | 管理 


| SSH (22) | KVM | ハイパーバイザーサーバーノードに展開 | ハイパーバイザーサーバーにアクセス 


| TLS (443) | ESXi または KVM | OTSノードとクラスタにデプロイする | ONTAPにアクセス 


| TLS (443) | ESXi または KVM | 展開する各OTSノード | アクセスデプロイ（容量プールライセンス） 


| iSCSI (3260) | ESXi または KVM | 展開する各OTSノード | メディエーター/メールボックスディスク 
|===