---
sidebar: sidebar 
permalink: reference_chk_select_req_info.html 
keywords: ontap select, pre-installation, vmware 
summary: VMware 環境にONTAP Selectクラスタを導入する準備の一環として、 ONTAP Select Deploy 管理ユーティリティを使用してクラスタを導入および設定するときに必要な情報を収集します。 
---
= ONTAP Selectのインストールに必要な情報
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
VMware 環境にONTAP Selectクラスタを導入する準備の一環として、 ONTAP Select Deploy 管理ユーティリティを使用してクラスタを導入および設定するときに必要な情報を収集します。

収集する情報の一部はクラスター自体に適用されますが、その他の情報はクラスター内の個々のノードに適用されます。



== クラスターレベルの情報

ONTAP Selectクラスタに関連する情報を収集する必要があります。

[cols="35,65"]
|===
| クラスタ情報 | 説明 


| クラスターの名前 | クラスターの一意の識別子。 


| ライセンスモード | 評価または購入したライセンス。 


| クラスターのIP構成 | クラスタとノードのIP構成。これには以下が含まれます: * クラスタの管理IPアドレス * サブネットマスク * デフォルトゲートウェイ 
|===


== ホストレベルの情報

ONTAP Selectクラスタ内の各ノードに関連する情報を収集する必要があります。

[cols="35,65"]
|===
| クラスタ情報 | 説明 


| ホスト名 | ホストの一意の識別子。 


| ホストのドメイン名 | ホストの完全修飾ドメイン名。 


| ノードのIP設定 | クラスター内の各ノードの管理 IP アドレス。 


| ミラーノード | HA ペア内の関連ノードの名前 (マルチノード クラスターのみ)。 


| ストレージ プール | 使用されているストレージ プールの名前。 


| ストレージディスク | ソフトウェア RAID を使用している場合のディスクのリスト。 


| シリアル番号 | 購入したライセンスを使用して導入する場合は、 NetAppから提供される一意の 9 桁のシリアル番号。 
|===