---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: ONTAP Select Deploy 管理ユーティリティのインストール計画の一環として考慮する必要がある一般的な要件がいくつかあります。 
---
= ONTAP Select Deploy の一般的な要件と計画
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 管理ユーティリティのインストール計画の一環として考慮する必要がある一般的な要件がいくつかあります。



== DeployユーティリティとONTAP Selectクラスタのペアリング

Deploy ユーティリティのインスタンスをONTAP Selectクラスタとペアリングする場合、いくつかのオプションがあります。


NOTE: すべての導入シナリオにおいて、単一のONTAP Selectクラスタとそのクラスタ内のノードは、Deploy管理ユーティリティの1つのインスタンスでのみ管理できます。1つのクラスタを、Deployユーティリティの2つ以上の異なるインスタンスで管理することはできません。

.ONTAP Selectクラスタごとにユーティリティのインスタンスが1つ
各ONTAP Selectクラスタは、Deployユーティリティの専用インスタンスを使用して導入および管理できます。この1対1構成では、ユーティリティとクラスタの各ペアが明確に分離されます。この構成により、高度な分離レベルが実現され、障害ドメインが縮小されます。

.複数のONTAP Selectクラスタ用のユーティリティのインスタンス 1 つ
組織内の複数のONTAP Selectクラスタを、Deployユーティリティの単一のインスタンスで導入および管理できます。この1対多構成では、すべての処理データと設定データがDeployユーティリティの同じインスタンスで管理されます。


NOTE: Deploy ユーティリティの 1 つのインスタンスで、最大 400 個のONTAP Selectノードまたは 100 個のクラスターを管理できます。



== KVM環境に関連する要件

KVM ハイパーバイザー環境に Deploy 管理ユーティリティをインストールする前に、基本要件を確認し、展開の準備をする必要があります。

.展開の要件と制限
KVM 環境にONTAP Select Deploy ユーティリティをインストールする場合は、考慮すべき要件と制限がいくつかあります。

.Linux KVMホストサーバーのハードウェア要件
Linux KVMハイパーバイザーホストには、いくつかの最低限のリソース要件を満たす必要があります。ONTAPONTAP Selectを導入するホストが以下の基本要件を満たしていることを確認してください。

* Linux サーバー:
+
** ハードウェアとソフトウェアは64ビットである必要があります
** サーバは、ONTAP Selectノードに定義されているのと同じサポート対象バージョンに準拠する必要があります。


* 仮想CPU (2)
* 仮想メモリ（4GB）
* ストレージ（40GB）
* 「ダイナミックホスト構成プロトコル（DHCP）が有効になっています（静的IPアドレスを割り当てることもできます）」


.ネットワーク接続
Deploy 仮想マシン ネットワーク インターフェイスが設定されており、管理対象のONTAP Selectホストに接続できることを確認します。

.IPバージョン4のサポート
ONTAP Select DeployはIPバージョン4（IPv4）のみをサポートします。IPバージョン6（IPv6）はサポートされていません。この制限は、 ONTAP Selectに以下の影響を与えます。

* デプロイ VM の管理 LIF に IPv4 アドレスを割り当てる必要があります。
* Deploy では、 ONTAP LIF で IPv6 を使用するように設定されたONTAP Selectノードを作成できません。




== 必要な構成情報

導入計画の一環として、 ONTAP Select Deploy 管理ユーティリティをインストールする前に、必要な設定情報を決定する必要があります。

.デプロイVMの名前
VM に使用する名前。

.Linux KVMホストの名前
デプロイ ユーティリティがインストールされている Linux KVM ホスト。

.ストレージプールの名前
VM ファイルを保持するストレージ プール (約 40 GB 必要)。

.VMのネットワーク
デプロイ VM が接続されているネットワーク。



== オプションのネットワーク構成情報

デプロイVMはデフォルトでDHCPを使用して構成されます。ただし、必要に応じてVMのネットワークインターフェースを手動で構成することもできます。

.ホスト名
ホストの名前。

.ホストのIPアドレス
静的 IPv4 アドレス。

.サブネット マスク
VM が属するネットワークに基づくサブネット マスク。

.ゲートウェイ
デフォルトゲートウェイまたはルーター。

.プライマリDNSサーバー
プライマリ ドメイン ネーム サーバー。

.セカンダリDNSサーバー
セカンダリ ドメイン ネーム サーバー。

.検索ドメイン
使用する検索ドメイン。



== 資格情報ストアを使用した認証

ONTAP Select Deployの認証情報ストアは、アカウント情報を保持するデータベースです。Deployは、クラスタの作成と管理の一環として、このアカウント認証情報を使用してホスト認証を実行します。ONTAPONTAP Selectの導入計画においては、認証情報ストアの使用方法を理解しておく必要があります。


NOTE: アカウント情報は、AES 暗号化アルゴリズムと SHA-256 ハッシュ アルゴリズムを使用してデータベースに安全に保存されます。

.資格情報の種類
次の種類の資格情報がサポートされています。

* ホストONTAP SelectノードをVMware ESXiに直接導入する際にハイパーバイザーホストを認証するために使用されます。
* vCenter ホストが VMware vCenter によって管理されている場合に、 ONTAP Selectノードを ESXi に導入する際に vCenter サーバーを認証するために使用されます。


.アクセス
資格情報ストアは、Deploy を使用した通常の管理タスク（ハイパーバイザーホストの追加など）の実行時に内部的にアクセスされます。また、Deploy の Web ユーザーインターフェースと CLI を介して資格情報ストアを直接管理することもできます。
