---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: ONTAP Selectホスト ストレージに関連して、考慮する必要がある計画上の問題がいくつかあります。 
---
= ONTAP SelectストレージとRAIDの考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectホスト ストレージに関連して、考慮する必要がある計画上の問題がいくつかあります。


NOTE: 外部ストレージのサポート情報については、link:reference_plan_ots_vnas.html["ONTAP Select vNAS の要件"] 。



== ハードウェアRAIDコントローラの要件

ONTAP Select を導入するハイパーバイザー ホスト上の RAID コントローラは、いくつかの要件を満たしている必要があります。


NOTE: ONTAP Selectが実行されるホストでは、ハードウェアRAIDコントローラまたはONTAP Selectに付属のソフトウェアRAID機能を使用する場合、ローカル物理ドライブが必要です。ONTAPONTAP Select vNASソリューションを使用して外部ストレージにアクセスする場合、ローカルRAIDコントローラとソフトウェアRAID機能は使用されません。

RAID コントローラの最小要件は次のとおりです。

* 12 Gbpsのスループット
* 512 MBの内部バッテリバックアップまたはフラッシュ（SuperCAP）キャッシュ
* 書き戻しモードに設定:
+
** フェイルバック モードを「ライト スルー」に有効にする (サポートされている場合)
** 「常に先読み」ポリシーを有効にする（サポートされている場合）


* RAID コントローラの背後にあるすべてのローカル ディスクは、単一の RAID グループとして構成する必要があります。必要に応じて複数の RAID コントローラを使用することもできます。
+
** データの整合性を維持するために不可欠な、RAID グループのローカル ドライブ キャッシュを無効にします。


* LUN 構成は、次のガイドラインに基づいて実行する必要があります。
+
** RAID グループのサイズが最大 LUN サイズの 64 TB を超える場合は、RAID グループ内の使用可能なストレージをすべて消費する、同じサイズの複数の LUN を構成する必要があります。
** RAID グループのサイズが最大 LUN サイズの 64 TB より小さい場合は、RAID グループ内の使用可能なストレージをすべて消費する 1 つの LUN を構成する必要があります。






== ソフトウェアRAIDの要件

ハイパーバイザー上にONTAP Selectクラスタを導入する場合、ローカルのハードウェアRAIDコントローラの代わりに、 ONTAP Selectが提供するソフトウェアRAID機能を利用できます。ソフトウェアRAIDを使用してクラスタを導入する前に、いくつかの要件と制限事項に注意する必要があります。



=== 一般要件

ソフトウェア RAID 展開環境は、次のコア要件を満たしている必要があります。

* VMware ESXi 7.0 GA (ビルド 15843807) 以降
* ONTAP Selectプレミアムライセンス以上
* ローカル SSD ドライブのみ
* システムディスクをルートおよびデータアグリゲートから分離
* ホストにハードウェア RAID コントローラがありません



NOTE: ハードウェアRAIDコントローラが存在する場合は、link:concept_stor_concepts_chars.html["ディープダイブストレージ"]追加の構成要件については、セクションを参照してください。



=== ESXi固有の要件

* VMware ESXi 7.0 GA (ビルド 15843807) 以降
* VMware VMotion、HA、DRSはサポートされていません
* ONTAP Select 9.4以前からアップグレードしたノードではソフトウェアRAIDを使用できません。その場合は、ソフトウェアRAIDを導入するために新しいノードを作成する必要があります。




=== KVM固有の要件

には特定の構成要件もあります。参照link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["Linuxサーバーの準備"]詳細については、手順を参照してください。

KVMに対するメディアの期待:: 使用する SSD フラッシュ ストレージ デバイスは、次の追加要件を満たしている必要があります。
+
--
* SSD デバイスは、次の方法で Linux ホストに正確かつ永続的に自分自身を報告する必要があります。
+
** # cat /sys/block/<デバイス>/queue/rotational
+
これらのコマンドに対して報告される値は '0' である必要があります。



* デバイスはHBA、または場合によってはJBODモードで動作するように設定されたRAIDコントローラに接続されていることが想定されます。RAIDコントローラを使用する場合、デバイスの機能はRAID機能をオーバーレイすることなくホストを経由する必要があります。RAIDコントローラをJBODモードで使用する場合は、RAIDのドキュメントを確認するか、必要に応じてベンダーに連絡して、デバイスの回転速度が「0」と報告されていることを確認してください。
* 2 つの個別のストレージ コンポーネントがあります。
+
** 仮想マシンストレージ
+
これは、ONTAP Select仮想マシンをホストするために使用されるシステムデータを含むLVMプール（ストレージプール）です。LVMプールは、高耐久性フラッシュデバイスでバックアップされている必要があり、SAS、SATA、NVMeのいずれかを使用できます。パフォーマンスを向上させるには、NVMeデバイスの使用を推奨します。

** データディスク
+
これはデータ管理に使用されるSASまたはSATA SSDドライブのセットです。SSDデバイスはエンタープライズグレードで耐久性に優れている必要があります。NVMeインターフェースはサポートされていません。



* すべてのデバイスは 512BPS でフォーマットする必要があります。


--




=== ONTAP Selectノード構成

システム ディスクをルート アグリゲートおよびデータ アグリゲートから分離するには、各ONTAP Selectノードとハイパーバイザ ホストを次のように設定する必要があります。

* システムストレージプールを作成するONTAP Selectシステムデータ用のストレージプールを作成する必要があります。ONTAP Selectノードの設定の一環として、ストレージプールを接続する必要があります。
* 必要な物理ディスクを接続します。ハイパーバイザーホストには、ONTAP Select仮想マシンで使用できる必要なSSDディスクが接続され、使用可能になっている必要があります。これらのドライブには、ルートアグリゲートとデータアグリゲートが保存されます。ONTAPONTAP Selectノードの設定の一環として、ストレージディスクを接続する必要があります。




== ストレージ容量の制限

ONTAP Select の導入計画の一環として、ストレージの割り当てと使用に関する制限に注意する必要があります。

最も重要な保管制限は以下に記載されています。また、link:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]より詳しい情報については。


TIP: ONTAP Select、ストレージの割り当てと使用に関するいくつかの制限が適用されます。ONTAPONTAP Selectクラスタを導入したりライセンスを購入したりする前に、これらの制限について理解しておく必要があります参照link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["ライセンス"]詳細についてはセクションをご覧ください。



=== 生のストレージ容量を計算する

ONTAP Selectのストレージ容量は、ONTAP Select仮想マシンに接続された仮想データディスクとルートディスクの許容サイズの合計に相当します。容量を割り当てる際には、この点を考慮する必要があります。



=== 単一ノードクラスタの最小ストレージ容量

単一ノード クラスター内のノードに割り当てられるストレージ プールの最小サイズは次のとおりです。

* 評価: 500 GB
* 生産量: 1.0 TB


実稼働環境の導入における最小割り当ては、ユーザー データ用の 1 TB と、さまざまなONTAP Select内部プロセスで使用される約 266 GB で構成され、これは必要なオーバーヘッドと見なされます。



=== マルチノードクラスタの最小ストレージ容量

マルチノード クラスター内の各ノードに割り当てられるストレージ プールの最小サイズは次のとおりです。

* 評価: 1.9 TB
* 生産量: 2.0 TB


実稼働環境の導入における最小割り当ては、ユーザー データ用の 2 TB と、さまざまなONTAP Select内部プロセスで使用される約 266 GB で構成され、これは必要なオーバーヘッドと見なされます。

[NOTE]
====
HA ペアの各ノードは同じストレージ容量を持つ必要があります。

HAペアのストレージ容量を見積もる際には、すべてのアグリゲート（ルートとデータ）がミラーリングされていることを考慮する必要があります。その結果、アグリゲートの各プレックスは均等なストレージ容量を消費します。

たとえば、2 TB のアグリゲートを作成すると、2 つのプレックス インスタンスに 2 TB (プレックス 0 に 2 TB、プレックス 1 に 2 TB)、つまりライセンスされたストレージの合計量の 4 TB が割り当てられます。

====


=== ストレージ容量と複数のストレージプール

ローカル直接接続ストレージ、VMware vSAN、または外部ストレージアレイを使用する場合、各ONTAP Selectノードは最大400TBのストレージを使用するように設定できます。ただし、直接接続ストレージまたは外部ストレージアレイを使用する場合、1つのストレージプールの最大サイズは64TBです。したがって、これらの状況で64TBを超えるストレージを使用する予定の場合は、次のように複数のストレージプールを割り当てる必要があります。

* クラスター作成プロセス中に初期ストレージプールを割り当てます
* 1つ以上の追加ストレージプールを割り当ててノードストレージを増やす



NOTE: 各ストレージプールには未使用の2%バッファが確保されており、容量ライセンスは必要ありません。このストレージは、容量上限が指定されていない限り、 ONTAP Selectによって使用されません。容量上限が指定されている場合は、指定された容量が2%バッファゾーンに収まらない限り、指定された容量のストレージが使用されます。このバッファは、ストレージプール内のすべてのスペースを割り当てようとする際に発生する可能性のあるエラーを防ぐために必要です。



=== ストレージ容量と VMware vSAN

VMware vSANを使用する場合、データストアは64TBを超える容量を持つことができます。ただし、 ONTAP Selectクラスタの作成時に最初に割り当てることができるのは最大64TBです。クラスタの作成後は、既存のvSANデータストアから追加のストレージを割り当てることができます。ONTAPONTAP Selectで使用できるvSANデータストアの容量は、VMストレージポリシーの設定に基づきます。



=== ベストプラクティス

ハイパーバイザー コア ハードウェアに関しては、次の推奨事項を考慮する必要があります。

* 単一のONTAP Selectアグリゲート内のすべてのドライブは同じタイプである必要があります。たとえば、同じアグリゲート内にHDDとSSDドライブを混在させることはできません。




== プラットフォームライセンスに基づく追加のディスクドライブ要件

選択するドライブは、プラットフォーム ライセンスの提供に基づいて制限されます。


NOTE: ディスクドライブの要件は、ローカルRAIDコントローラとドライブ、およびソフトウェアRAIDを使用する場合に適用されます。これらの要件は、ONTAP Select vNASソリューションを介してアクセスされる外部ストレージには適用されません。

.Standard
* 8～60 台の内蔵 HDD (NL-SAS、SATA、10K SAS)


.Premium
* 8～60 台の内蔵 HDD (NL-SAS、SATA、10K SAS)
* 4～60 台の内蔵 SSD


.プレミアムXL
* 8～60 台の内蔵 HDD (NL-SAS、SATA、10K SAS)
* 4～60 台の内蔵 SSD
* 4～14個の内部NVMe



NOTE: ローカル DAS ドライブを使用したソフトウェア RAID は、プレミアム ライセンス (SSD のみ) およびプレミアム XL ライセンス (SSD または NVMe) でサポートされます。



== ソフトウェアRAID搭載NVMeドライブ

NVMe SSDドライブを使用するようにソフトウェアRAIDを構成できます。環境は以下の要件を満たしている必要があります。

* サポートされているDeploy管理ユーティリティを備えたONTAP Select
* プレミアムXLプラットフォームライセンスまたは90日間の評価ライセンス
* VMware ESXi バージョン 6.7 以降
* 仕様1.0以降に準拠したNVMeデバイス


NVMe ドライブを使用する前に手動で構成する必要があります。見るlink:task_chk_nvme_configure.html["NVMeドライブを使用するようにホストを構成する"]詳細についてはこちらをご覧ください。
