---
sidebar: sidebar 
permalink: reference_lic_ontap_features.html 
keywords: license, licensing, ontap features, default ontap features 
summary: ONTAP Selectは、 ONTAPのほとんどの機能を完全にサポートしています。クラスタを導入すると、多くのONTAP機能のライセンスが各ノードに自動的に付与されます。ただし、一部の機能には別途ライセンスが必要です。 
---
= ONTAP SelectによるONTAP機能のサポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select はほとんどのONTAP機能をサポートしています。クラスタを導入すると、多くのONTAP機能のライセンスが各ノードに自動的に付与されます。ただし、一部の機能には別途ライセンスが必要です。


NOTE: ハードウェア固有の依存関係を持つONTAP機能は、通常、 ONTAP Selectではサポートされません。



== ONTAP機能はデフォルトで自動的に有効化されます

次のONTAP機能はONTAP Selectでサポートされており、デフォルトでライセンスが付与されます。

* 自律型ランサムウェア保護 (ARP) (手動更新)
* CIFS
* 重複排除と圧縮
* FlexCache
* FlexClone
* iSCSI
* NDMP
* NetAppボリューム暗号化 (制限のない国のみ)
* NFS
* NVMe over TCP
* ONTAPマルチテナンシー機能
* ONTAP S3
* S3 SnapMirror
* SnapMirror
* SnapMirrorクラウド
* SnapRestore
* SnapVault
* ストレージ VM 災害復旧 (SVM DR)
+

NOTE: ONTAP Selectは、ソースとデスティネーションの両方でSVM DRをサポートし、最大16個の関係を設定できます。SVMDRのサポートは、ソースONTAPバージョンがバージョン2以降の場合に限られます。例えば、ソースONTAP Select 9.12.1は、デスティネーションONTAPバージョン9.12.1、9.13.1、または9.14.1に接続できます。





== 別途ライセンスが必要なONTAPの機能

デフォルトで有効になっていない次のようなONTAP機能については、別途ライセンスを取得する必要があります。

* FabricPool
* MetroCluster SDS（ONTAP Selectプレミアムライセンス提供）


[NOTE]
====
* ONTAP Select 9.16.1以前では、 SnapLock Select Enterprise（改ざん防止スナップショットロックを含む）は、link:https://mysupport.netapp.com/site/["NetAppサポート サイト"^] 。
* SnapLock Compliance はONTAP Selectではサポートされていません。
* StorageGRIDを使用する場合、 FabricPoolライセンスは必要ありません。


====
.関連情報
* link:concept_ots_overview.html#compare-ontap-select-and-ontap-9["ONTAP SelectとONTAP 9の比較"]
* link:https://mysupport.netapp.com/site/systems/master-license-keys["NetApp ONTAPマスターライセンスキー"^]

