---
sidebar: sidebar 
permalink: reference_plan_best_practices.html 
keywords: plan, planning, best practices, recommendations 
summary: ONTAP Select の導入計画の一環として考慮すべきベスト プラクティスがあります。 
---
= ONTAP Select導入のベストプラクティスの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の導入計画の一環として考慮すべきベスト プラクティスがあります。



== ストレージ

ストレージに関しては、次のベスト プラクティスを考慮する必要があります。



=== オールフラッシュまたは汎用フラッシュアレイ

オールフラッシュ VSAN または汎用フラッシュ アレイを使用したONTAP Select仮想 NAS (vNAS) の展開では、SSD 以外の DAS ストレージを使用したONTAP Selectのベスト プラクティスに従う必要があります。



=== 外部ストレージ

次の推奨事項に従う必要があります。

* ONTAP Selectネットワークと外部ストレージの専用ネットワークポート、帯域幅、vSwitch構成を定義します。
* ストレージ使用率を制限するために容量オプションを設定します（ONTAP Selectは外部ストレージプールの全容量を消費することはできません）。
* すべての外部ストレージアレイが、可能な限り利用可能な冗長性とHA機能を使用していることを確認する




=== ハイパーバイザーコアハードウェア

単一のONTAP Selectアグリゲート内のドライブはすべて同じタイプである必要があります。たとえば、同じアグリゲート内にHDDとSSDドライブを混在させることはできません。



=== RAIDコントローラ

サーバーのRAIDコントローラはライトバックモードで動作するように設定する必要があります。書き込みワークロードのパフォーマンスに問題がある場合は、コントローラの設定を確認し、ライトスルーまたはライトアラウンドが有効になっていないことを確認してください。

物理サーバーに、ローカル接続されたすべてのディスクを管理する単一のRAIDコントローラーが搭載されている場合、 NetAppは、サーバーOS用とONTAP SelectのLUNを別々に作成することを推奨します。このベストプラクティスにより、ブートディスクが破損した場合でも、管理者はONTAP Selectに影響を与えることなくOS LUNを再作成できます。

RAIDコントローラのキャッシュは、 NVRAMパーティションを対象とするブロック変更だけでなく、すべての受信ブロック変更を保存するために使用されます。したがって、RAIDコントローラを選択する際には、キャッシュ容量が最も大きいものを選択してください。キャッシュ容量が大きいほど、ディスクフラッシュの頻度が減り、 ONTAP Select仮想マシン、ハイパーバイザー、そしてサーバー上で共存するすべてのコンピューティング仮想マシンのパフォーマンスが向上します。



=== RAIDグループ

最適なRAIDグループサイズは8～12台のドライブです。RAIDグループあたりの最大ドライブ数は24台です。

ONTAP Selectノードごとにサポートされる NVME ドライブの最大数は 14 です。

スペアディスクはオプションですが、推奨されます。NetAppNetApp、RAIDグループごとに1つのスペアディスクを使用することを推奨していますが、すべてのRAIDグループにグローバルスペアディスクを使用することもできます。例えば、RAIDグループ3つごとにスペアディスクを2つ使用し、各RAIDグループを8～12台のドライブで構成することができます。

ONTAP Select、 RAIDグループ内のLUN数を増やしてもパフォーマンス上のメリットはありません。複数のLUNは、SATA/NL-SAS構成のベストプラクティスに従う場合、またはハイパーバイザーのファイルシステムの制限を回避する場合にのみ使用してください。



=== VMware ESXi ホスト

NetAppでは、システム ディスクをホストするデータストアにはESX 6.5 U2以降とNVMeディスクを使用することを推奨しています。この構成では、 NVRAMパーティションに最適なパフォーマンスが提供されます。


NOTE: ESX 6.5 U2以降にインストールする場合、 ONTAP SelectはシステムディスクがSSD上にあるかNVMeディスク上にあるかに関係なく、vNVMEeドライバを使用します。これにより、VMのハードウェアレベルはESX 6.5以降と互換性のある13に設定されます。

ONTAP Selectネットワークと外部ストレージ (iSCSI または NFS を使用する場合の VMware vSAN および汎用ストレージ アレイ トラフィック) 専用のネットワーク ポート、帯域幅、および vSwitch 構成を定義します。

ストレージ使用率を制限するように容量オプションを設定します (ONTAP Select は外部 vNAS データストアの全容量を消費できません)。

すべての汎用外部ストレージ アレイが、可能な限り、利用可能な冗長性と HA 機能を使用していることを確認します。



=== VMware Storage vMotion

ONTAP SelectノードでVMware Storage vMotionを使用するかどうかを判断する際、新しいホストの利用可能な容量だけが考慮されるわけではありません。基盤となるストレージタイプ、ホスト構成、ネットワーク機能は、元のホストと同じワークロードを維持できる必要があります。



== ネットワーク

ネットワークに関しては、次のベスト プラクティスを考慮する必要があります。



=== 重複したMACアドレス

複数の Deploy インスタンスが重複した MAC アドレスを割り当てる可能性を排除するには、レイヤー 2 ネットワークごとに 1 つの Deploy インスタンスを使用して、 ONTAP Selectクラスタまたはノードを作成または管理する必要があります。



=== EMSメッセージ

ONTAP Selectの2ノードクラスタでは、ストレージフェイルオーバーが無効であることを示すEMSメッセージがないか注意深く監視する必要があります。これらのメッセージは、メディエーターサービスへの接続が失われたことを示しているため、直ちに修正する必要があります。



=== ノード間の遅延

2つのノード間のネットワークは、平均5msのレイテンシと、それに加えて5msの周期ジッタをサポートする必要があります。クラスタを導入する前に、 ONTAP Selectの製品アーキテクチャとベストプラクティスに関するテクニカルレポートに記載されている手順に従ってネットワークをテストしてください。



=== 負荷分散

内部および外部のONTAP Selectネットワーク全体でロード バランシングを最適化するには、発信元仮想ポートに基づくルート ロード バランシング ポリシーを使用します。



=== 複数のレイヤー2ネットワーク

データ トラフィックが複数のレイヤー 2 ネットワークにまたがり、VLAN ポートの使用が必要な場合、または複数の IPspace を使用している場合は、VGT を使用する必要があります。



=== 物理スイッチの構成

VMware では、ESXi ホストに接続するスイッチ ポートの STP を Portfast に設定することを推奨しています。スイッチ ポートの STP を Portfast に設定しないと、 ONTAP Select のアップリンク障害耐性に影響する可能性があります。LACPを使用する場合は、LACP タイマーを高速（1 秒）に設定する必要があります。ロードバランシング ポリシーは、ポート グループで「IP ハッシュに基づくルート」に設定し、LAG で「送信元 IP アドレスと宛先 IP アドレス、TCP/UDP ポート、VLAN」に設定する必要があります



=== KVMの仮想スイッチオプション

外部ネットワークと内部ネットワーク（マルチノードクラスタのみ）をサポートするには、各ONTAP Selectホストに仮想スイッチを設定する必要があります。マルチノードクラスタの導入の一環として、内部クラスタネットワークのネットワーク接続をテストする必要があります。

ハイパーバイザーホスト上でOpen vSwitchを構成する方法の詳細については、link:https://www.netapp.com/media/13134-tr4613.pdf["KVM 上のONTAP Select製品のアーキテクチャとベストプラクティス"^]技術レポート。



== HA

高可用性のために、次のベスト プラクティスを考慮する必要があります。



=== バックアップを展開する

クラスターの作成後も含め、デプロイ構成データを定期的にバックアップすることがベストプラクティスです。これは、2ノードクラスタの場合、メディエーター構成データがバックアップに含まれるため、特に重要になります。

クラスタを作成または展開した後は、link:task_cli_clusters.html["ONTAP Select Deploy構成データをバックアップする"] 。



=== ミラーリングされたアグリゲート

プライマリアグリゲートの最新（RPO 0）コピーを提供するためにはミラーリングされたアグリゲートが必要ですが、プライマリアグリゲートの空きスペースが不足しないように注意してください。プライマリアグリゲートのスペースが不足すると、 ONTAPはストレージギブバックのベースラインとして使用されていた共通のSnapshotコピーを削除する可能性があります。これはクライアントからの書き込みに対応するために設計された動作です。ただし、フェイルバック時に共通のSnapshotコピーがない場合は、 ONTAP Selectノードはミラーリングされたアグリゲートから完全なベースラインを作成する必要があります。シェアードナッシング環境では、この処理にかなりの時間がかかる場合があります。


NOTE: NetApp、ストレージのパフォーマンスと可用性を最適化するために、ミラーリングされたアグリゲートに少なくとも20%の空きスペースを確保することを推奨しています。ミラーリングされていないアグリゲートの場合は10%が推奨されていますが、ファイルシステムは追加の10%のスペースを使用して増分変更を吸収できます。ミラーされたアグリゲートの場合、増分変更に際し、ONTAPのcopy-on-write Snapshotベースのアーキテクチャが理由でスペース使用率が増えます。これらのベストプラクティスに従わない場合、パフォーマンスに悪影響を与える可能性があります。高可用性テイクオーバーは、データアグリゲートがミラーリングされたアグリゲートとして構成されている場合にのみサポートされます。



=== NIC の集約、チーミング、フェイルオーバー

ONTAP Select は、2 ノード クラスタに対して単一の 10Gb リンクをサポートします。ただし、 ONTAP Selectクラスタの内部ネットワークと外部ネットワークの両方で NIC アグリゲーションまたは NIC チーミングを通じてハードウェア冗長性を確保することがNetApp のベスト プラクティスです。

NIC に複数の特定用途向け集積回路 (ASIC) がある場合は、内部ネットワークと外部ネットワークの NIC チーミングを通じてネットワーク構造を構築するときに、各 ASIC から 1 つのネットワーク ポートを選択します。

NetApp、ESXと物理スイッチの両方でLACPモードをアクティブにすることを推奨しています。さらに、物理スイッチ、ポート、ポートチャネルインターフェース、およびVMNICのLACPタイマーを高速（1秒）に設定する必要があります。

LACP で分散 vSwitch を使用する場合、 NetApp、ポート グループの IP ハッシュ、送信元と宛先の IP アドレス、TCP/UDP ポート、および LAG の VLAN に基づいてルートするようにロード バランシング ポリシーを設定することを推奨します。



=== 2ノードストレッチHA（MetroCluster SDS）のベストプラクティス

MetroCluster SDS を作成する前に、 ONTAP Deploy 接続チェッカーを使用して、2 つのデータセンター間のネットワーク遅延が許容範囲内であることを確認します。

仮想ゲストタギング（VGT）と2ノードクラスタを使用する場合は、追加の注意点があります。2ノードクラスタ構成では、 ONTAPが完全に利用可能になる前に、ノード管理IPアドレスを使用してメディエータへの早期接続を確立します。そのため、ノード管理LIF（ポートe0a）にマッピングされたポートグループでは、外部スイッチタギング（EST）と仮想スイッチタギング（VST）のみがサポートされます。さらに、管理トラフィックとデータトラフィックの両方が同じポートグループを使用している場合、2ノードクラスタ全体でESTとVSTのみがサポートされます。
