---
sidebar: sidebar 
permalink: reference_plan_ots_general.html 
keywords: plan, planning, general requirements 
summary: ONTAP Select の導入計画の一環として考慮する必要がある一般的な要件がいくつかあります。 
---
= ONTAP Selectの要件と計画上の考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select の導入を計画する際に考慮する必要がある一般的な要件がいくつかあります。



== KVMに必要なLinuxの知識とスキル

KVM ハイパーバイザーを備えた Linux は、作業が複雑な環境です。KVM にONTAP Selectを導入する前に、必要な知識とスキルが必要です。

Linuxサーバーディストリビューション:: ONTAP Selectの導入に使用する特定のLinuxディストリビューションの使用経験が必要です。具体的には、以下のタスクを実行できる必要があります。
+
--
* Linuxディストリビューションをインストールする
* CLIを使用してシステムを構成する
* ソフトウェアパッケージと依存関係を追加する


--


Linuxサーバーの準備に関する詳細情報（必要な構成やソフトウェアパッケージなど）については、ホスト構成チェックリストをご覧ください。現在サポートされているLinuxディストリビューションのハイパーバイザー要件もご確認ください。

KVMの導入と管理:: 仮想化の一般的な概念を理解している必要があります。また、KVM環境でONTAP Selectをインストールおよび管理する際には、以下のLinux CLIコマンドを使用する必要があります。
+
--
* `virt-install`
* `virsh`
* `lsblk`
* `lvs`
* `vgs`
* `pvs`


--
ネットワークとOpen vSwitchの構成:: ネットワークの概念とネットワークスイッチの設定に精通している必要があります。また、Open vSwitchの使用経験も必要です。KVM環境でONTAP Selectネットワークを設定する際には、以下のネットワークコマンドを使用する必要があります。
+
--
* `ovs-vsctl`
* `ip`
* `ip link`
* `systemctl`


--




== クラスターのサイズと関連する考慮事項

クラスター サイズに関連して、考慮すべき計画上の問題がいくつかあります。

クラスター内のノード数:: ONTAP Selectクラスタは、1、2、4、6、または8ノードで構成されます。クラスタのサイズは、アプリケーションの要件に基づいて決定する必要があります。例えば、エンタープライズ環境でHA機能が必要な場合は、マルチノードクラスタを使用する必要があります。
専用とコロケーション:: アプリケーションの種類に応じて、デプロイメントを専用モデルと併置モデルのどちらにするかを決定する必要があります。併置モデルは、ワークロードの多様性と緊密な統合により、より複雑になる可能性があることに注意してください。




== ハイパーバイザーホストの考慮事項

ハイパーバイザー ホストに関連して、考慮すべき計画上の問題がいくつかあります。


CAUTION: NetAppサポートからの指示がない限り、 ONTAP Select仮想マシンの設定を直接変更しないでください。仮想マシンの設定と変更は、必ずDeploy管理ユーティリティを使用して行ってください。NetAppサポートの支援なしに、 NetAppユーティリティを使用せずにONTAP Select仮想マシンに変更を加えると、仮想マシンに障害が発生し、使用できなくなる可能性があります。

ハイパーバイザーに依存しない:: ONTAP SelectとONTAP Select Deploy管理ユーティリティはどちらもハイパーバイザーに依存しません。以下のハイパーバイザーはどちらもサポートされています。
+
--
* VMware ESXi
* カーネルベースの仮想マシン (KVM)


--



NOTE: ONTAP Select 9.14.1以降、KVMハイパーバイザーのサポートが復活しました。以前は、KVMハイパーバイザーへの新規クラスタの導入のサポートはONTAP Select 9.10.1で削除され、既存のKVMクラスタおよびホストの管理（オフライン化または削除を除く）のサポートはONTAP Select 9.11.1で削除されていました。

サポートされているプラットフォームに関する詳細については、ハイパーバイザー固有の計画情報とリリース ノートを参照してください。

ONTAP Selectノードおよび管理ユーティリティ用のハイパーバイザー:: Deploy管理ユーティリティとONTAP Selectノードはどちらも仮想マシンとして動作します。Deployユーティリティ用に選択するハイパーバイザーは、 ONTAP Selectノード用に選択するハイパーバイザーとは独立しています。この2つを組み合わせる際には、以下の柔軟性が確保されています。
+
--
* VMware ESXi上で実行されるデプロイユーティリティは、VMware ESXiまたはKVM上でONTAP Selectクラスタを作成および管理できます。
* KVM上で実行される導入ユーティリティは、VMware ESXiまたはKVM上でONTAP Selectクラスタを作成および管理できます。


--
ホストごとに 1 つ以上のONTAP Selectノードのインスタンス:: 各ONTAP Selectノードは専用の仮想マシンとして実行されます。同じハイパーバイザーホスト上に複数のノードを作成できますが、以下の制限があります。
+
--
* 単一のONTAP Selectクラスタの複数のノードを同じホスト上で実行することはできません。特定のホスト上のすべてのノードは、異なるONTAP Selectクラスタに属している必要があります。
* 外部ストレージを使用する必要があります。
* ソフトウェア RAID を使用する場合、ホストに導入できるONTAP Selectノードは 1 つだけです。


--
クラスタ内のノードのハイパーバイザーの一貫性:: ONTAP Selectクラスタ内のすべてのホストは、同じバージョンおよびリリースのハイパーバイザ ソフトウェアで実行する必要があります。
各ホストの物理ポートの数:: 各ホストは、1つ、2つ、または4つの物理ポートを使用するように設定する必要があります。ネットワークポートの設定は柔軟に行うことができますが、可能な限り以下の推奨事項に従ってください。
+
--
* 単一ノード クラスター内のホストには 2 つの物理ポートが必要です。
* マルチノードクラスタ内の各ホストには4つの物理ポートが必要です


--
ONTAP SelectとONTAPハードウェアベースクラスタの統合:: ONTAP SelectノードをONTAPハードウェアベースクラスタに直接追加することはできません。ただし、オプションでONTAP SelectクラスタとハードウェアベースONTAPクラスタの間にクラスタピア関係を確立することは可能です。




== 保管に関する考慮事項

ホスト ストレージに関連して、考慮すべき計画上の問題がいくつかあります。

RAIDタイプ:: ESXiで直接接続ストレージ（DAS）を使用する場合は、ローカルハードウェアRAIDコントローラを使用するか、 ONTAP Selectに含まれるソフトウェアRAID機能を使用するかを決定する必要があります。ソフトウェアRAIDを使用する場合は、link:reference_plan_ots_storage.html["ストレージとRAIDの考慮事項"]詳細についてはこちらをご覧ください。
ローカルストレージ:: RAID コントローラによって管理されるローカル ストレージを使用する場合は、次のことを決定する必要があります。
+
--
* 1つまたは複数のRAIDグループを使用するかどうか
* 1つまたは複数のLUNを使用するかどうか


--
外部ストレージ:: ONTAP Select vNASソリューションを使用する場合、リモートデータストアの配置場所とアクセス方法を決定する必要があります。ONTAPONTAP Select vNASは、以下の構成をサポートしています。
+
--
* VMware vSAN
* 汎用外部ストレージアレイ


--
必要なストレージの見積もり:: ONTAP Selectノードに必要なストレージ容量を決定する必要があります。この情報は、ストレージ容量を含むライセンスの購入時に必要となります。詳細については、「ストレージ容量の制限」を参照してください。



NOTE: ONTAP Selectストレージ容量は、 ONTAP Select仮想マシンに接続されているデータ ディスクの合計許容サイズに対応します。

実稼働展開のライセンス モデル:: 本番環境に導入された各ONTAP Selectクラスタごとに、容量階層または容量プールのライセンスモデルを選択する必要があります。詳細については、「ライセンス」セクションをご覧ください。




== 資格情報ストアを使用した認証

ONTAP Select Deployの認証情報ストアは、アカウント情報を保持するデータベースです。Deployは、クラスタの作成と管理の一環として、このアカウント認証情報を使用してホスト認証を実行します。ONTAPONTAP Selectの導入計画においては、認証情報ストアの使用方法を理解しておく必要があります。


NOTE: アカウント情報は、Advanced Encryption Standard (AES) 暗号化アルゴリズムと SHA-256 ハッシュ アルゴリズムを使用してデータベースに安全に保存されます。

資格情報の種類:: 次の種類の資格情報がサポートされています。
+
--
* ホスト
+
*ホスト* 認証情報は、 ONTAP Selectノードを ESXi または KVM に直接導入する際の一部としてハイパーバイザー ホストを認証するために使用されます。

* vcenter
+
*vcenter* 認証情報は、ホストが VMware vCenter によって管理されている場合に、 ONTAP Selectノードを ESXi に展開する際の一部として vCenter サーバーを認証するために使用されます。



--
アクセス:: 資格情報ストアは、Deploy を使用した通常の管理タスク（ハイパーバイザーホストの追加など）の実行時に内部的にアクセスされます。また、Deploy の Web ユーザーインターフェースと CLI を介して資格情報ストアを直接管理することもできます。


.関連情報
* link:reference_plan_ots_storage.html["ストレージとRAIDの考慮事項"]

