= ステップ1：アップグレードパッケージをダウンロードする
:allow-uri-read: 


サイドバー: サイドバー パーマリンク: task_cli_upgrade_deploy.html キーワード: 管理、管理、cli、デプロイ、アップグレード デプロイの概要：コマンド ライン インターフェイスを使用して、既存の Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。--- = ONTAP Select Deploy インスタンスをアップグレードします :hardbreaks: :nofooter: :icons: font :linkattrs: :imagesdir: ./media/

[role="lead"]
ONTAP Select Deploy ユーティリティ CLI を使用して、既存の ONTAP Select Deploy ユーティリティ仮想マシンをインプレースでアップグレードします。

.開始する前に
アップグレード中に ONTAP Select Deploy が他のタスクの実行に使用されていないことを確認します。ONTAP Select Deploy ユーティリティのアップグレードに関する情報と制限事項については、link:reference_release_notes.html["リリース ノート"]を参照してください。

[NOTE]
====
ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、最新リリースにアップグレードする必要があります。ONTAPONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます見るlink:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^]詳細については、こちらをご覧ください。

ONTAP Select Deploy 9.17.1または9.16.1からONTAP Select Deploy 9.18.1に直接アップグレードできます。ONTAP Select Deploy 9.15.1以前からアップグレードする場合は、お使いのONTAP Selectバージョンのリリースノートを確認してください。

====


== ステップ1：アップグレードパッケージをダウンロードする

アップグレードプロセスを開始するには、NetApp Support SiteからONTAP Select Deployアップグレードファイルをダウンロードします。アップグレードパッケージは、単一の圧縮ファイルとしてフォーマットされます。

.手順
. link:https://mysupport.netapp.com/site/downloads/["NetApp Support Site ダウンロード"^]ページにアクセスします。
. 下にスクロールして*ONTAP Select Deploy*を選択してください。
. 希望する ONTAP Select バージョンを選択してください。
. エンド ユーザー ライセンス契約 (EULA) を確認し、[同意して続行] を選択します。
. 適切な*ONTAP Select Deploy Upgrade*パッケージを選択してダウンロードします。必要に応じてすべてのプロンプトに応答します。




== ステップ2: ONTAP Select Deploy仮想マシンにパッケージをアップロードする

パッケージをダウンロードしたら、そのファイルをONTAP Select Deploy 仮想マシンにアップロードする必要があります。

.タスク概要
このタスクでは、ファイルをONTAP Select Deploy 仮想マシンにアップロードする 1 つの方法について説明します。ご使用の環境に適した他のオプションがある可能性があります。

.開始する前に
* アップグレード ファイルがローカル ワークステーションで使用可能であることを確認します。
* 管理者ユーザー アカウントのパスワードがあることを確認します。


.手順
. ローカルワークステーションのコマンドシェルで、 `scp` (Secure Copy Protocol) ユーティリティを使用して、次の例に示すように、イメージ ファイルをONTAP Select Deploy 仮想マシンにアップロードします。
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレード ファイルは、管理者ユーザーのホーム ディレクトリに保存されます。



== ステップ3: アップグレードパッケージを適用する

アップグレード ファイルをONTAP Select Deploy 仮想マシンにアップロードしたら、アップグレードを適用できます。

.開始する前に
* ONTAP Select Deploy ユーティリティ仮想マシンのどのディレクトリにアップグレード ファイルが配置されているかを確認します。
* アップグレードの実行中に、 ONTAP Select Deploy を使用して他のタスクが実行されていないことを確認します。


.手順
. 管理者アカウントで SSH を使用してONTAP Select Deploy ユーティリティ CLI にSign in。
. 適切なディレクトリ パスとファイル名を使用してアップグレードを実行します。
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
コマンド例:

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.終了後の操作
アップグレード手順が完了する前に、 ONTAP Select Deploy 仮想マシン構成のバックアップを作成するように求められます。また、新しく作成されたONTAP Select Deploy ページを表示できるように、ブラウザのキャッシュをクリアする必要があります。
