---
sidebar: sidebar 
permalink: task_adm_connectivity.html 
keywords: administer, administering, web, connectivity, network connectivity, network checker 
summary: 内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、操作の失敗につながる可能性のある問題を検出します。 
---
= ONTAP Selectノード間の接続を確認する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、操作の失敗につながる可能性のある問題を検出します。

.開始する前に
テストに含まれるすべてのONTAP Selectノードが設定され、電源がオンになっている必要があります。

.タスク概要
テストを開始するたびに、バックグラウンドで新しいプロセス実行が作成され、一意の実行IDが割り当てられます。一度にアクティブにできる実行は1つだけです。

テストには、その動作を制御する 2 つのモードがあります。

* クイック このモードでは、基本的な無停止テストを実行します。PINGテストに加え、ネットワークMTUサイズとvSwitchのテストも実行されます。
* 拡張モード：このモードでは、すべての冗長ネットワークパスに対してより包括的なテストを実行します。アクティブなONTAP Selectクラスタでこのテストを実行すると、クラスタのパフォーマンスに影響が出る可能性があります。



NOTE: マルチノードクラスタを作成する前に、必ずクイックテストを実行することをお勧めします。クイックテストが正常に完了したら、必要に応じて、本番環境の要件に基づいて拡張テストを実行できます。

.手順
. 管理者アカウントを使用して、デプロイ ユーティリティの Web ユーザー インターフェイスにSign in。
. ページ上部の*管理*タブをクリックし、*ネットワーク チェッカー*をクリックします。
. *新規実行を開始*をクリックし、HAペアのホストとネットワークを選択します。
+
必要に応じて、追加の HA ペアを追加して構成できます。

. *開始* をクリックして、ネットワーク接続テストを開始します。

