---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: ONTAP SelectイメージをDeploy管理ユーティリティのインスタンスに追加できます。インストールしたイメージは、 ONTAP Selectクラスタの導入時に使用できます。 
---
= ONTAP Selectイメージをデプロイに追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP SelectイメージをDeploy管理ユーティリティのインスタンスに追加できます。インストールしたイメージは、 ONTAP Selectクラスタの導入時に使用できます。

.開始する前に
新しいONTAP Selectイメージを Deploy に追加する前に、まず不要なイメージを削除する必要があります。


NOTE: Deployユーティリティのインスタンスに含まれている元のバージョンよりも前のバージョンのONTAP Selectイメージのみを追加してください。NetAppNetApp提供される新しいバージョンのONTAP Selectを追加することは、サポートされていない構成です。



== ステップ1: インストールイメージをダウンロードする

ONTAP SelectイメージをDeployユーティリティのインスタンスに追加するプロセスを開始するには、 NetAppサポートサイトからインストールイメージをダウンロードする必要があります。ONTAPONTAP Selectインストールイメージは、単一の圧縮ファイルとしてフォーマットされています。

.手順
. Web ブラウザを使用してNetAppサポート サイトにアクセスし、*サポート クイック リンク* を選択します。
. *トップタスク*の下にある*ソフトウェアのダウンロード*を選択し、サイトにサインインします。
. *製品を探す*を選択します。
. 下にスクロールして* ONTAP Select*を選択します。
. *その他の利用可能なソフトウェアを選択* の下で、*デプロイのアップグレード、ノードのアップグレード、イメージのインストール* を選択します。
. アップグレード パッケージの希望するリリースを選択します。
. エンド ユーザー ライセンス契約 (EULA) を確認し、[同意して続行] をクリックします。
. 環境に応じて必要に応じてすべてのプロンプトに応答し、適切なパッケージを選択してダウンロードします。




== ステップ2: インストールイメージをデプロイにアップロードする

ONTAP Selectインストール イメージを取得したら、そのファイルを Deploy 仮想マシンにアップロードする必要があります。

.開始する前に
インストールイメージファイルがローカルワークステーション上に用意されている必要があります。また、Deploy管理者ユーザーアカウントのパスワードも必要です。

.タスク概要
このタスクでは、Deploy仮想マシンにファイルをアップロードする方法の一つを説明します。環境によっては、より適切な他の方法がある場合があります。

.手順
. ローカル ワークステーションのコマンド シェルで、次の例に示すように、イメージ ファイルを Deploy 仮想マシンにアップロードします。
+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.結果
ノードインストールファイルは、管理者ユーザーのホームディレクトリに保存されます。



== ステップ3: インストールイメージを追加する

新しいクラスタを展開するときに使用できるように、 ONTAP Selectインストール イメージを Deploy イメージ ディレクトリに追加します。

.開始する前に
インストールイメージファイルがDeployユーティリティ仮想マシンのどのディレクトリに配置されているかを確認する必要があります。ファイルは管理者のホームディレクトリにあるものと想定されます。

.手順
. 管理者 (admin) アカウントで SSH を使用して、デプロイ ユーティリティ CLI にSign in。
. Bash シェルを起動します。


[listing]
----
shell bash
----
. 次の例に示すように、インストール イメージ ファイルを images ディレクトリに配置します。
+
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== ステップ4: 利用可能なインストールイメージを表示する

新しいクラスタを展開するときに使用できるONTAP Selectイメージを表示します。

.手順
. デプロイ ユーティリティ仮想マシンのオンライン ドキュメント Web ページにアクセスし、管理者 (admin) アカウントを使用してサインインします。
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
デプロイ仮想マシンのドメイン名または IP アドレスを使用します。

. ページの下部に移動して *デプロイ* を選択し、次に *GET /images* を選択します。
. 利用可能なONTAP Selectイメージを表示するには、「*試してみる*」を選択します。
. 希望する画像が利用可能であることを確認します。

