---
sidebar: sidebar 
permalink: task_adm_resize.html 
keywords: administer, administering, web, resizing nodes, resizing 
summary: ONTAP Selectクラスタを展開した後、展開管理ユーティリティを使用してノードのハイパーバイザ インスタンス タイプをアップグレードできます。 
---
= ONTAP Selectクラスタノードのサイズを変更する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectクラスタを展開した後、展開管理ユーティリティを使用してノードのハイパーバイザ インスタンス タイプをアップグレードできます。


NOTE: 容量階層ライセンス モデルおよび容量プール ライセンス モデルを使用している場合は、クラスター ノードのサイズ変更操作を実行できます。


NOTE: 大規模インスタンス タイプへのサイズ変更は、ESXi でのみサポートされます。

.開始する前に
クラスターはオンライン状態である必要があります。

.タスク概要
このタスクでは、Deploy ウェブユーザーインターフェースの使用方法を説明します。また、Deploy CLI を使用してインスタンスのサイズ変更を行うこともできます。どのインターフェースを使用する場合でも、サイズ変更操作に必要な時間はいくつかの要因によって大きく異なり、完了までに長時間かかる場合があります。ノードのサイズは、より大きなサイズにのみ変更できます。

.手順
. 管理者アカウントを使用して、デプロイ ユーティリティの Web ユーザー インターフェイスにSign in。
. ページ上部の*クラスター*タブをクリックし、リストから目的のクラスターを選択します。
. クラスターの詳細ページで、ページの右側にある歯車アイコンをクリックし、*インスタンスのサイズ変更*を選択します。
. *インスタンス タイプ* を選択し、 ONTAP認証情報を入力して、*変更* をクリックします。


.終了後の操作
サイズ変更操作が完了するまで待つ必要があります。
