---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドラインインターフェイスを使用して、既存の Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。 
---
= ONTAP Select Deployインスタンスをアップグレードする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy ユーティリティ CLI を使用して、既存の ONTAP Select Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。

.開始する前に
アップグレード中は、ONTAP Select Deployを他のタスクの実行に使用しないでください。ONTAP Select Deployユーティリティのアップグレードに関する情報と制限事項については、最新のリリースノートを参照してください。

[NOTE]
====
ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、最新リリースにアップグレードする必要があります。ONTAPONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます見るlink:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^]詳細については、こちらをご覧ください。

ONTAP Select Deploy 9.16.1または9.15.1からONTAP Select Deploy 9.17.1に直接アップグレードできます。ONTAP Select Deploy 9.14.1以前からアップグレードする場合は、お使いのONTAP Selectバージョンのリリースノートを確認してください。

====


== ステップ1：パッケージをダウンロードする

アップグレードプロセスを開始するには、link:https://mysupport.netapp.com/site/["NetAppサポート サイト"^]から適切なONTAP Select Deploy仮想マシンのアップグレードファイルをダウンロードします。アップグレードパッケージは、単一の圧縮ファイルとしてフォーマットされます。

.手順
. Web ブラウザを使用してlink:https://mysupport.netapp.com/site/["NetAppサポート サイト"^]にアクセスし、Downloads メニューから *Downloads* を選択します。
. 下にスクロールして*ONTAP Select Deploy Upgrade*を選択してください。
. アップグレード パッケージの目的のリリースを選択します。
. エンド ユーザー ライセンス契約 (EULA) を確認し、[同意して続行] を選択します。
. 適切なパッケージを選択してダウンロードし、環境に応じて必要なすべてのプロンプトに応答します。




== ステップ2: ONTAP Select Deploy仮想マシンにパッケージをアップロードする

パッケージをダウンロードしたら、そのファイルをONTAP Select Deploy 仮想マシンにアップロードする必要があります。

.タスク概要
このタスクでは、ファイルをONTAP Select Deploy 仮想マシンにアップロードする 1 つの方法について説明します。ご使用の環境に適した他のオプションがある可能性があります。

.開始する前に
* アップグレード ファイルがローカル ワークステーションで使用可能であることを確認します。
* 管理者ユーザー アカウントのパスワードがあることを確認します。


.手順
. ローカルワークステーションのコマンドシェルで、 `scp` (Secure Copy Protocol) ユーティリティを使用して、次の例に示すように、イメージ ファイルをONTAP Select Deploy 仮想マシンにアップロードします。
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレード ファイルは、管理者ユーザーのホーム ディレクトリに保存されます。



== ステップ3: アップグレードパッケージを適用する

アップグレード ファイルをONTAP Select Deploy 仮想マシンにアップロードしたら、アップグレードを適用できます。

.開始する前に
* ONTAP Select Deploy ユーティリティ仮想マシンのどのディレクトリにアップグレード ファイルが配置されているかを確認します。
* アップグレードの実行中に、 ONTAP Select Deploy を使用して他のタスクが実行されていないことを確認します。


.手順
. 管理者アカウントで SSH を使用してONTAP Select Deploy ユーティリティ CLI にSign in。
. 適切なディレクトリ パスとファイル名を使用してアップグレードを実行します。
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
コマンド例:

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.終了後の操作
アップグレード手順が完了する前に、 ONTAP Select Deploy 仮想マシン構成のバックアップを作成するように求められます。また、新しく作成されたONTAP Select Deploy ページを表示できるように、ブラウザのキャッシュをクリアする必要があります。
