---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、操作の失敗につながる可能性のある問題を検出します。 
---
= ONTAP Selectノード間のネットワーク接続を確認する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
内部クラスタネットワーク上の2つ以上のONTAP Selectノード間のネットワーク接続をテストできます。通常、このテストはマルチノードクラスタを導入する前に実行し、操作の失敗につながる可能性のある問題を検出します。

.開始する前に
テストに含まれるすべてのONTAP Selectノードが設定され、電源がオンになっている必要があります。

.タスク概要
テストを開始するたびに、バックグラウンドで新しいプロセス実行が作成され、一意の実行IDが割り当てられます。一度にアクティブにできる実行は1つだけです。

テストには、その動作を制御する 2 つのモードがあります。

* クイック このモードでは、基本的な無停止テストを実行します。PINGテストに加え、ネットワークMTUサイズとvSwitchのテストも実行されます。
* 拡張モード：このモードでは、すべての冗長ネットワークパスに対してより包括的なテストを実行します。アクティブなONTAP Selectクラスタでこのテストを実行すると、クラスタのパフォーマンスに影響が出る可能性があります。



NOTE: マルチノードクラスタを作成する前に、必ずクイックテストを実行することをお勧めします。クイックテストが正常に完了したら、必要に応じて、本番環境の要件に基づいて拡張テストを実行できます。

.手順
. 管理者アカウントを使用して、デプロイ ユーティリティ CLI にSign in。
. ネットワーク接続チェッカーの現在の実行を表示し、アクティブな実行がないことを確認します。
+
`network connectivity-check show`

. ネットワーク接続チェッカーを起動し、コマンド出力の実行 ID をメモします。
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
例

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. 実行 ID に基づいてネットワーク接続チェッカーの進行状況を監視します。
+
`network connectivity-check show -run-id RUN_ID`



.終了後の操作
ネットワーク接続チェッカーは通常、 ONTAP-Internal ポートグループに追加された一時ポートとIPアドレスを削除することでクリーンアップを行います。ただし、接続チェッカーが一時ポートの削除に失敗した場合は、CLIコマンドをオプション付きで再実行して手動でクリーンアップ操作を実行する必要があります。 `-mode cleanup` 。ONTAP内部ポート グループから一時ポートを削除しないと、 ONTAP Select仮想マシンが正常に作成されない可能性があります。
