---
sidebar: sidebar 
permalink: task_lic_acquire_cp.html 
keywords: license, licensing, acquire, Capacity Pools 
summary: ONTAP Selectノードで使用される容量プールごとにライセンスファイルを取得する必要があります。ライセンスファイルは、プールのストレージ容量と有効期限を定義します。ライセンスファイルは、NetAppによって割り当てられた一意のライセンスシリアル番号と、Deployインスタンスに関連付けられたライセンスロックIDの組み合わせによって、License Managerにロックされます。 
---
= ONTAP Select容量プールライセンスを取得する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Selectノードで使用される容量プールごとにライセンスファイルを取得する必要があります。ライセンスファイルは、プールのストレージ容量と有効期限を定義します。ライセンスファイルは、NetAppによって割り当てられた一意のライセンスシリアル番号と、Deployインスタンスに関連付けられたライセンスロックIDの組み合わせによって、License Managerにロックされます。

.開始する前に
NetAppによって容量プールに割り当てられた9桁のライセンスシリアル番号が必要です。ライセンスファイルを取得する前に、注文書の発送日から少なくとも24時間お待ちください。

.タスク概要
ONTAP Selectノードで使用される容量プールごとにこのタスクを実行する必要があります。

.手順
. Web ブラウザを使用してNetAppサポート サイトにアクセスし、サインインします。
. 上部の*システム*をクリックし、*ソフトウェア ライセンス*をクリックします。
. 容量プールのライセンス シリアル番号を入力し、[Go!] をクリックします。
. ライセンスの詳細ページで、*製品の詳細*列に移動します。
. 適切な行の* NetAppライセンス ファイルの取得*をクリックします。
. ONTAP Select Deploy インスタンスのライセンス ロック ID を入力し、[送信] をクリックします。
. 適切な配送方法を選択し、「送信」をクリックします。
. 配信確認ウィンドウで[*OK*]をクリックします。


.終了後の操作
容量プールをONTAP Selectノードで使用するには、ライセンス ファイルを Deploy 管理ユーティリティにアップロードする必要があります。
