---
sidebar: sidebar 
permalink: task_lic_acquire_ct.html 
keywords: license, licensing, acquire, Capacity Tiers 
summary: 容量階層ライセンスを使用する場合、 ONTAP Selectノードごとにライセンスファイルを取得する必要があります。ライセンスファイルはノードのストレージ容量を定義し、 NetAppによって割り当てられた9桁の一意のシリアル番号によってノードにロックされます。 
---
= ONTAP Select容量階層ライセンスを取得する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量階層ライセンスを使用する場合、 ONTAP Selectノードごとにライセンスファイルを取得する必要があります。ライセンスファイルはノードのストレージ容量を定義し、 NetAppによって割り当てられた9桁の一意のシリアル番号によってノードにロックされます。

.開始する前に
NetAppによってノードに割り当てられた9桁のライセンスシリアル番号が必要です。ライセンスファイルを取得する前に、注文書の発送日から少なくとも24時間お待ちください。

.タスク概要
容量階層ライセンスを必要とするONTAP Selectノードごとにこのタスクを実行する必要があります。

.手順
. Web ブラウザを使用してONTAP Selectライセンス サイトにアクセスします。
+
`https://register.netapp.com/register/getlicensefile`

. NetAppアカウントのクレデンシャルを使用してサインインします。
. *ライセンス ジェネレーター* ページで、ドロップダウン ボックスから必要なライセンス オファリングを選択します。
. ONTAP Selectノードのシリアル番号である *製品シリアル番号* を含め、同じページの残りのフィールドに入力します。
. *送信*をクリックします。
. リクエストが検証されたら、ライセンスの配信方法を選択します。
+
*ライセンスのダウンロード*または*ライセンスの電子メール送信*のいずれかをクリックできます。

. 選択した配送方法に基づいてライセンス ファイルを受信したことを確認します。


.終了後の操作
ライセンス ファイルをONTAP Selectノードに適用する前に、Deploy 管理ユーティリティにアップロードする必要があります。
