---
sidebar: sidebar 
permalink: task_cli_migrate_deploy.html 
keywords: administer, administering, cli, deploy, deploy instance, migrate 
summary: コマンドライン インターフェイスを使用して、Deploy 管理ユーティリティの既存のインスタンスを新しい仮想マシンに移行できます。 
---
= ONTAP Select Deployインスタンスを新しい仮想マシンに移行する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コマンドライン インターフェイスを使用して、Deploy 管理ユーティリティの既存のインスタンスを新しい仮想マシンに移行できます。

この手順は、元の仮想マシンの構成データを使用して新しい仮想マシンを作成することを前提としています。新しい仮想マシンと元の仮想マシンは、同じバージョンとリリースのDeployユーティリティを実行する必要があります。異なるバージョンとリリースのDeployユーティリティに移行することはできません。



== ステップ1: デプロイ構成データをバックアップする

仮想マシンの移行の一環として、Deploy構成データのバックアップを作成する必要があります。また、 ONTAP Selectクラスタの導入後にもバックアップを作成する必要があります。データは単一の暗号化ファイルに保存され、ローカルワークステーションにダウンロードできます。

.開始する前に
* バックアップ操作中に Deploy が他のタスクを実行していないことを確認してください。
* 元のデプロイ仮想マシン イメージを保存します。
+

CAUTION: 元の Deploy 仮想マシン イメージは、この手順の後半で、元の仮想マシンから新しい仮想マシンに Deploy 構成データを復元するときに必要になります。



.タスク概要
作成するバックアップファイルには、仮想マシンのすべての構成データが保存されます。このデータは、 ONTAP Selectクラスタを含む導入環境のさまざまな側面を表します。

.手順
. 管理者アカウントで SSH を使用して、デプロイ ユーティリティ CLI にSign in。
. デプロイ サーバーの内部ディレクトリに保存されているデプロイ構成データのバックアップを作成します。
+
[source, cli]
----
deploy backup create
----
. プロンプトが表示されたら、バックアップのパスワードを入力します。
+
バックアップ ファイルはパスワードに基づいて暗号化されます。

. システムで利用可能なバックアップを表示します。
+
[source, cli]
----
deploy backup show -detailed
----
. *作成*フィールドの日付に基づいてバックアップ ファイルを選択し、*ダウンロード URL* の値を記録します。
+
URL を通じてバックアップ ファイルにアクセスできます。

. Web ブラウザまたは Curl などのユーティリティを使用して、URL を指定してバックアップ ファイルをローカル ワークステーションにダウンロードします。




== ステップ2: Deploy仮想マシンの新しいインスタンスをインストールする

元の仮想マシンの構成データを使用して更新できる、デプロイ仮想マシンの新しいインスタンスを作成する必要があります。

.開始する前に
VMware 環境でONTAP Select Deploy 仮想マシンをダウンロードして展開する手順を理解している必要があります。

.タスク概要
このタスクは高レベルで説明されています。

.手順
. デプロイ仮想マシンの新しいインスタンスを作成します。
+
.. 仮想マシンイメージをダウンロードします。
.. 仮想マシンをデプロイし、ネットワーク インターフェイスを構成します。
.. SSH を使用してデプロイ ユーティリティにアクセスします。




.関連情報
link:task_install_deploy.html["ONTAP Select Deploy をインストールする"]



== ステップ3: デプロイ構成データを新しい仮想マシンに復元する

元のDeployユーティリティ仮想マシンから新しい仮想マシンに構成データを復元する必要があります。データは1つのファイルに保存されており、ローカルワークステーションからアップロードする必要があります。

.開始する前に
以前のバックアップからの設定データが必要です。データは単一のファイルにまとめられており、ローカルワークステーション上で利用できる必要があります。

.手順
. 次の例に示すように、ローカル ワークステーションのコマンド シェルで、sftp ユーティリティを使用して、バックアップ ファイルを Deploy 仮想マシンにアップロードします。
+
....
sftp admin@10.234.81.101 (provide password when prompted)
put deploy_backup_20190601162151.tar.gz
exit
....
. 管理者アカウントで SSH を使用して、デプロイ ユーティリティ CLI にSign in。
. 構成データを復元します。
+
[source, cli]
----
deploy backup restore -path <path_name> -filename <file_name>
----
+
コマンドの例

+
`deploy backup restore -path /home/admin -filename deploy_backup_20180601162151.tar.gz`


