---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: コマンドライン インターフェイスを使用して、既存の Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。 
---
= ONTAP Select Deployインスタンスをアップグレードする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select ONTAP Select Select Deploy ユーティリティ仮想マシンをインプレースでアップグレードできます。

.開始する前に
アップグレード中にONTAP Select Deploy を使用して他のタスクを実行しないようにしてください。ONTAP Select Deploy ユーティリティのアップグレードに関する情報と制限については、最新のリリース ノートを参照してください。

[NOTE]
====
ONTAP Select Deploy管理ユーティリティの古いインスタンスがインストールされている場合は、最新リリースにアップグレードする必要があります。ONTAPONTAP SelectノードとONTAP Select Deployコンポーネントは個別にアップグレードされます見るlink:concept_adm_upgrading_nodes.html["ONTAP Selectノードをアップグレードする"^]詳細については、こちらをご覧ください。

ONTAP Select Deploy 9.16.1 または 9.15.1 からONTAP Select Deploy 9.17.1 に直接アップグレードできます。ONTAP Select Deploy 9.14.1 以前からアップグレードするには、 ONTAP Selectバージョンのリリース ノートを確認してください。

====


== ステップ1: パッケージをダウンロードする

アップグレードプロセスを開始するには、適切なONTAP Select Deploy仮想マシンアップグレードファイルをlink:https://mysupport.netapp.com/site/["NetAppサポート サイト"^]。アップグレード パッケージは、単一の圧縮ファイルとしてフォーマットされます。

.手順
. アクセスlink:https://mysupport.netapp.com/site/["NetAppサポート サイト"^]Web ブラウザを使用して、[ダウンロード] メニューから [*ダウンロード*] を選択します。
. 下にスクロールして* ONTAP Select Deploy Upgrade*を選択します。
. アップグレード パッケージの希望するリリースを選択します。
. エンド ユーザー ライセンス契約 (EULA) を確認し、[同意して続行] を選択します。
. 環境に応じて必要に応じてすべてのプロンプトに応答し、適切なパッケージを選択してダウンロードします。




== ステップ2: ONTAP Select Deploy仮想マシンにパッケージをアップロードする

パッケージをダウンロードしたら、そのファイルをONTAP Select Deploy 仮想マシンにアップロードする必要があります。

.タスク概要
このタスクでは、ファイルをONTAP Select Deploy 仮想マシンにアップロードする 1 つの方法について説明します。ご使用の環境に適した他のオプションがある可能性があります。

.開始する前に
* アップグレード ファイルがローカル ワークステーションで使用可能であることを確認します。
* 管理者ユーザー アカウントのパスワードがあることを確認します。


.手順
. ローカルワークステーションのコマンドシェルで、 `scp` (Secure Copy Protocol) ユーティリティを使用して、次の例に示すように、イメージ ファイルをONTAP Select Deploy 仮想マシンにアップロードします。
+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
アップグレード ファイルは、管理者ユーザーのホーム ディレクトリに保存されます。



== ステップ3: アップグレードパッケージを適用する

アップグレード ファイルをONTAP Select Deploy 仮想マシンにアップロードしたら、アップグレードを適用できます。

.開始する前に
* ONTAP Select Deploy ユーティリティ仮想マシンのどのディレクトリにアップグレード ファイルが配置されているかを確認します。
* アップグレードの実行中に、 ONTAP Select Deploy を使用して他のタスクが実行されていないことを確認します。


.手順
. 管理者アカウントで SSH を使用してONTAP Select Deploy ユーティリティ CLI にSign in。
. 適切なディレクトリ パスとファイル名を使用してアップグレードを実行します。
+
[source, cli]
----
deploy upgrade -package-path <file_path>
----
+
コマンド例:

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.終了後の操作
アップグレード手順が完了する前に、 ONTAP Select Deploy 仮想マシン構成のバックアップを作成するように求められます。また、新しく作成されたONTAP Select Deploy ページを表示できるように、ブラウザのキャッシュをクリアする必要があります。
